// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/annotation.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/annotation.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {

inline constexpr AnnotationProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_{nullptr},
        id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR AnnotationProto::AnnotationProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AnnotationProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnnotationProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnnotationProtoDefaultTypeInternal() {}
  union {
    AnnotationProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnnotationProtoDefaultTypeInternal _AnnotationProto_default_instance_;

inline constexpr AnnotationMapProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        annotations_{},
        struct_fields_{},
        array_element_{nullptr},
        is_null_{false} {}

template <typename>
PROTOBUF_CONSTEXPR AnnotationMapProto::AnnotationMapProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AnnotationMapProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnnotationMapProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnnotationMapProtoDefaultTypeInternal() {}
  union {
    AnnotationMapProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnnotationMapProtoDefaultTypeInternal _AnnotationMapProto_default_instance_;
}  // namespace googlesql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_googlesql_2fpublic_2fannotation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2fannotation_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2fannotation_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationProto, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationProto, _impl_.value_),
        1,
        0,
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationMapProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationMapProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationMapProto, _impl_.is_null_),
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationMapProto, _impl_.annotations_),
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationMapProto, _impl_.array_element_),
        PROTOBUF_FIELD_OFFSET(::googlesql::AnnotationMapProto, _impl_.struct_fields_),
        1,
        ~0u,
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::googlesql::AnnotationProto)},
        {12, 24, -1, sizeof(::googlesql::AnnotationMapProto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::_AnnotationProto_default_instance_._instance,
    &::googlesql::_AnnotationMapProto_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2fannotation_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n!googlesql/public/annotation.proto\022\tgoo"
    "glesql\032#googlesql/public/simple_value.pr"
    "oto\"I\n\017AnnotationProto\022\n\n\002id\030\001 \001(\003\022*\n\005va"
    "lue\030\002 \001(\0132\033.googlesql.SimpleValueProto\"\306"
    "\001\n\022AnnotationMapProto\022\017\n\007is_null\030\004 \001(\010\022/"
    "\n\013annotations\030\001 \003(\0132\032.googlesql.Annotati"
    "onProto\0228\n\rarray_element\030\002 \001(\0132\035.googles"
    "ql.AnnotationMapProtoB\002\030\001\0224\n\rstruct_fiel"
    "ds\030\003 \003(\0132\035.googlesql.AnnotationMapProtoB"
    ".\n\024com.google.googlesqlB\023GoogleSQLAnnota"
    "tion\370\001\001"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2fannotation_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fpublic_2fsimple_5fvalue_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2fannotation_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2fannotation_2eproto = {
    false,
    false,
    407,
    descriptor_table_protodef_googlesql_2fpublic_2fannotation_2eproto,
    "googlesql/public/annotation.proto",
    &descriptor_table_googlesql_2fpublic_2fannotation_2eproto_once,
    descriptor_table_googlesql_2fpublic_2fannotation_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2fannotation_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2fannotation_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2fannotation_2eproto,
};
namespace googlesql {
// ===================================================================

class AnnotationProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AnnotationProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_._has_bits_);
};

void AnnotationProto::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.value_ != nullptr) _impl_.value_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
AnnotationProto::AnnotationProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.AnnotationProto)
}
inline PROTOBUF_NDEBUG_INLINE AnnotationProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::AnnotationProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

AnnotationProto::AnnotationProto(
    ::google::protobuf::Arena* arena,
    const AnnotationProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AnnotationProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.value_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::SimpleValueProto>(
                              arena, *from._impl_.value_)
                        : nullptr;
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:googlesql.AnnotationProto)
}
inline PROTOBUF_NDEBUG_INLINE AnnotationProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AnnotationProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, value_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, value_) +
               sizeof(Impl_::id_));
}
AnnotationProto::~AnnotationProto() {
  // @@protoc_insertion_point(destructor:googlesql.AnnotationProto)
  SharedDtor(*this);
}
inline void AnnotationProto::SharedDtor(MessageLite& self) {
  AnnotationProto& this_ = static_cast<AnnotationProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.value_;
  this_._impl_.~Impl_();
}

inline void* AnnotationProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AnnotationProto(arena);
}
constexpr auto AnnotationProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AnnotationProto),
                                            alignof(AnnotationProto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AnnotationProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AnnotationProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AnnotationProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AnnotationProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AnnotationProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AnnotationProto>(), &AnnotationProto::ByteSizeLong,
            &AnnotationProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_._cached_size_),
        false,
    },
    &AnnotationProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fannotation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AnnotationProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> AnnotationProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::AnnotationProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .googlesql.SimpleValueProto value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_.value_)}},
    // optional int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AnnotationProto, _impl_.id_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_.id_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .googlesql.SimpleValueProto value = 2;
    {PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::SimpleValueProto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void AnnotationProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.AnnotationProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.value_ != nullptr);
    _impl_.value_->Clear();
  }
  _impl_.id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AnnotationProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AnnotationProto& this_ = static_cast<const AnnotationProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AnnotationProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AnnotationProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.AnnotationProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int64 id = 1;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // optional .googlesql.SimpleValueProto value = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.value_, this_._impl_.value_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.AnnotationProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AnnotationProto::ByteSizeLong(const MessageLite& base) {
          const AnnotationProto& this_ = static_cast<const AnnotationProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AnnotationProto::ByteSizeLong() const {
          const AnnotationProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.AnnotationProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional .googlesql.SimpleValueProto value = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.value_);
            }
            // optional int64 id = 1;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AnnotationProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnnotationProto*>(&to_msg);
  auto& from = static_cast<const AnnotationProto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.AnnotationProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.value_ != nullptr);
      if (_this->_impl_.value_ == nullptr) {
        _this->_impl_.value_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::SimpleValueProto>(arena, *from._impl_.value_);
      } else {
        _this->_impl_.value_->MergeFrom(*from._impl_.value_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.id_ = from._impl_.id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AnnotationProto::CopyFrom(const AnnotationProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.AnnotationProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AnnotationProto::InternalSwap(AnnotationProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_.id_)
      + sizeof(AnnotationProto::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(AnnotationProto, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::google::protobuf::Metadata AnnotationProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AnnotationMapProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AnnotationMapProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_._has_bits_);
};

AnnotationMapProto::AnnotationMapProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.AnnotationMapProto)
}
inline PROTOBUF_NDEBUG_INLINE AnnotationMapProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::AnnotationMapProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        annotations_{visibility, arena, from.annotations_},
        struct_fields_{visibility, arena, from.struct_fields_} {}

AnnotationMapProto::AnnotationMapProto(
    ::google::protobuf::Arena* arena,
    const AnnotationMapProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AnnotationMapProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.array_element_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::AnnotationMapProto>(
                              arena, *from._impl_.array_element_)
                        : nullptr;
  _impl_.is_null_ = from._impl_.is_null_;

  // @@protoc_insertion_point(copy_constructor:googlesql.AnnotationMapProto)
}
inline PROTOBUF_NDEBUG_INLINE AnnotationMapProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        annotations_{visibility, arena},
        struct_fields_{visibility, arena} {}

inline void AnnotationMapProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, array_element_),
           0,
           offsetof(Impl_, is_null_) -
               offsetof(Impl_, array_element_) +
               sizeof(Impl_::is_null_));
}
AnnotationMapProto::~AnnotationMapProto() {
  // @@protoc_insertion_point(destructor:googlesql.AnnotationMapProto)
  SharedDtor(*this);
}
inline void AnnotationMapProto::SharedDtor(MessageLite& self) {
  AnnotationMapProto& this_ = static_cast<AnnotationMapProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.array_element_;
  this_._impl_.~Impl_();
}

inline void* AnnotationMapProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AnnotationMapProto(arena);
}
constexpr auto AnnotationMapProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.annotations_) +
          decltype(AnnotationMapProto::_impl_.annotations_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.struct_fields_) +
          decltype(AnnotationMapProto::_impl_.struct_fields_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(AnnotationMapProto), alignof(AnnotationMapProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AnnotationMapProto::PlacementNew_,
                                 sizeof(AnnotationMapProto),
                                 alignof(AnnotationMapProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AnnotationMapProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AnnotationMapProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AnnotationMapProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AnnotationMapProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AnnotationMapProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AnnotationMapProto>(), &AnnotationMapProto::ByteSizeLong,
            &AnnotationMapProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_._cached_size_),
        false,
    },
    &AnnotationMapProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fannotation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AnnotationMapProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 3, 0, 2> AnnotationMapProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::AnnotationMapProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bool is_null = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AnnotationMapProto, _impl_.is_null_), 1>(),
     {32, 1, 0, PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.is_null_)}},
    // repeated .googlesql.AnnotationProto annotations = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.annotations_)}},
    // optional .googlesql.AnnotationMapProto array_element = 2 [deprecated = true];
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 1, PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.array_element_)}},
    // repeated .googlesql.AnnotationMapProto struct_fields = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 2, PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.struct_fields_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .googlesql.AnnotationProto annotations = 1;
    {PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.annotations_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .googlesql.AnnotationMapProto array_element = 2 [deprecated = true];
    {PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.array_element_), _Internal::kHasBitsOffset + 0, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .googlesql.AnnotationMapProto struct_fields = 3;
    {PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.struct_fields_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bool is_null = 4;
    {PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.is_null_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::AnnotationProto>()},
    {::_pbi::TcParser::GetTable<::googlesql::AnnotationMapProto>()},
    {::_pbi::TcParser::GetTable<::googlesql::AnnotationMapProto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void AnnotationMapProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.AnnotationMapProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.annotations_.Clear();
  _impl_.struct_fields_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.array_element_ != nullptr);
    _impl_.array_element_->Clear();
  }
  _impl_.is_null_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AnnotationMapProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AnnotationMapProto& this_ = static_cast<const AnnotationMapProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AnnotationMapProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AnnotationMapProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.AnnotationMapProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .googlesql.AnnotationProto annotations = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_annotations_size());
               i < n; i++) {
            const auto& repfield = this_._internal_annotations().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .googlesql.AnnotationMapProto array_element = 2 [deprecated = true];
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.array_element_, this_._impl_.array_element_->GetCachedSize(), target,
                stream);
          }

          // repeated .googlesql.AnnotationMapProto struct_fields = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_struct_fields_size());
               i < n; i++) {
            const auto& repfield = this_._internal_struct_fields().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // optional bool is_null = 4;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_is_null(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.AnnotationMapProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AnnotationMapProto::ByteSizeLong(const MessageLite& base) {
          const AnnotationMapProto& this_ = static_cast<const AnnotationMapProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AnnotationMapProto::ByteSizeLong() const {
          const AnnotationMapProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.AnnotationMapProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.AnnotationProto annotations = 1;
            {
              total_size += 1UL * this_._internal_annotations_size();
              for (const auto& msg : this_._internal_annotations()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .googlesql.AnnotationMapProto struct_fields = 3;
            {
              total_size += 1UL * this_._internal_struct_fields_size();
              for (const auto& msg : this_._internal_struct_fields()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional .googlesql.AnnotationMapProto array_element = 2 [deprecated = true];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.array_element_);
            }
            // optional bool is_null = 4;
            if (cached_has_bits & 0x00000002u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AnnotationMapProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnnotationMapProto*>(&to_msg);
  auto& from = static_cast<const AnnotationMapProto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.AnnotationMapProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_annotations()->MergeFrom(
      from._internal_annotations());
  _this->_internal_mutable_struct_fields()->MergeFrom(
      from._internal_struct_fields());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.array_element_ != nullptr);
      if (_this->_impl_.array_element_ == nullptr) {
        _this->_impl_.array_element_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::AnnotationMapProto>(arena, *from._impl_.array_element_);
      } else {
        _this->_impl_.array_element_->MergeFrom(*from._impl_.array_element_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.is_null_ = from._impl_.is_null_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AnnotationMapProto::CopyFrom(const AnnotationMapProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.AnnotationMapProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AnnotationMapProto::InternalSwap(AnnotationMapProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.annotations_.InternalSwap(&other->_impl_.annotations_);
  _impl_.struct_fields_.InternalSwap(&other->_impl_.struct_fields_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.is_null_)
      + sizeof(AnnotationMapProto::_impl_.is_null_)
      - PROTOBUF_FIELD_OFFSET(AnnotationMapProto, _impl_.array_element_)>(
          reinterpret_cast<char*>(&_impl_.array_element_),
          reinterpret_cast<char*>(&other->_impl_.array_element_));
}

::google::protobuf::Metadata AnnotationMapProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2fannotation_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
