// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/annotation.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2fannotation_2eproto_2epb_2eh
#define googlesql_2fpublic_2fannotation_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "googlesql/public/simple_value.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2fannotation_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2fannotation_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2fannotation_2eproto;
namespace googlesql {
class AnnotationMapProto;
struct AnnotationMapProtoDefaultTypeInternal;
extern AnnotationMapProtoDefaultTypeInternal _AnnotationMapProto_default_instance_;
class AnnotationProto;
struct AnnotationProtoDefaultTypeInternal;
extern AnnotationProtoDefaultTypeInternal _AnnotationProto_default_instance_;
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {

// ===================================================================


// -------------------------------------------------------------------

class AnnotationProto final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql.AnnotationProto) */ {
 public:
  inline AnnotationProto() : AnnotationProto(nullptr) {}
  ~AnnotationProto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AnnotationProto* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AnnotationProto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnnotationProto(
      ::google::protobuf::internal::ConstantInitialized);

  inline AnnotationProto(const AnnotationProto& from) : AnnotationProto(nullptr, from) {}
  inline AnnotationProto(AnnotationProto&& from) noexcept
      : AnnotationProto(nullptr, std::move(from)) {}
  inline AnnotationProto& operator=(const AnnotationProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnnotationProto& operator=(AnnotationProto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnnotationProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnnotationProto* internal_default_instance() {
    return reinterpret_cast<const AnnotationProto*>(
        &_AnnotationProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AnnotationProto& a, AnnotationProto& b) { a.Swap(&b); }
  inline void Swap(AnnotationProto* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnnotationProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnnotationProto* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AnnotationProto>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AnnotationProto& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AnnotationProto& from) { AnnotationProto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AnnotationProto* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.AnnotationProto"; }

 protected:
  explicit AnnotationProto(::google::protobuf::Arena* arena);
  AnnotationProto(::google::protobuf::Arena* arena, const AnnotationProto& from);
  AnnotationProto(::google::protobuf::Arena* arena, AnnotationProto&& from) noexcept
      : AnnotationProto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // optional .googlesql.SimpleValueProto value = 2;
  bool has_value() const;
  void clear_value() ;
  const ::googlesql::SimpleValueProto& value() const;
  PROTOBUF_NODISCARD ::googlesql::SimpleValueProto* release_value();
  ::googlesql::SimpleValueProto* mutable_value();
  void set_allocated_value(::googlesql::SimpleValueProto* value);
  void unsafe_arena_set_allocated_value(::googlesql::SimpleValueProto* value);
  ::googlesql::SimpleValueProto* unsafe_arena_release_value();

  private:
  const ::googlesql::SimpleValueProto& _internal_value() const;
  ::googlesql::SimpleValueProto* _internal_mutable_value();

  public:
  // optional int64 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::int64_t id() const;
  void set_id(::int64_t value);

  private:
  ::int64_t _internal_id() const;
  void _internal_set_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:googlesql.AnnotationProto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AnnotationProto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::googlesql::SimpleValueProto* value_;
    ::int64_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fpublic_2fannotation_2eproto;
};
// -------------------------------------------------------------------

class AnnotationMapProto final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql.AnnotationMapProto) */ {
 public:
  inline AnnotationMapProto() : AnnotationMapProto(nullptr) {}
  ~AnnotationMapProto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AnnotationMapProto* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AnnotationMapProto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnnotationMapProto(
      ::google::protobuf::internal::ConstantInitialized);

  inline AnnotationMapProto(const AnnotationMapProto& from) : AnnotationMapProto(nullptr, from) {}
  inline AnnotationMapProto(AnnotationMapProto&& from) noexcept
      : AnnotationMapProto(nullptr, std::move(from)) {}
  inline AnnotationMapProto& operator=(const AnnotationMapProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnnotationMapProto& operator=(AnnotationMapProto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnnotationMapProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnnotationMapProto* internal_default_instance() {
    return reinterpret_cast<const AnnotationMapProto*>(
        &_AnnotationMapProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AnnotationMapProto& a, AnnotationMapProto& b) { a.Swap(&b); }
  inline void Swap(AnnotationMapProto* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnnotationMapProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnnotationMapProto* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AnnotationMapProto>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AnnotationMapProto& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AnnotationMapProto& from) { AnnotationMapProto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AnnotationMapProto* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.AnnotationMapProto"; }

 protected:
  explicit AnnotationMapProto(::google::protobuf::Arena* arena);
  AnnotationMapProto(::google::protobuf::Arena* arena, const AnnotationMapProto& from);
  AnnotationMapProto(::google::protobuf::Arena* arena, AnnotationMapProto&& from) noexcept
      : AnnotationMapProto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAnnotationsFieldNumber = 1,
    kStructFieldsFieldNumber = 3,
    kArrayElementFieldNumber = 2,
    kIsNullFieldNumber = 4,
  };
  // repeated .googlesql.AnnotationProto annotations = 1;
  int annotations_size() const;
  private:
  int _internal_annotations_size() const;

  public:
  void clear_annotations() ;
  ::googlesql::AnnotationProto* mutable_annotations(int index);
  ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>* mutable_annotations();

  private:
  const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>& _internal_annotations() const;
  ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>* _internal_mutable_annotations();
  public:
  const ::googlesql::AnnotationProto& annotations(int index) const;
  ::googlesql::AnnotationProto* add_annotations();
  const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>& annotations() const;
  // repeated .googlesql.AnnotationMapProto struct_fields = 3;
  int struct_fields_size() const;
  private:
  int _internal_struct_fields_size() const;

  public:
  void clear_struct_fields() ;
  ::googlesql::AnnotationMapProto* mutable_struct_fields(int index);
  ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>* mutable_struct_fields();

  private:
  const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>& _internal_struct_fields() const;
  ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>* _internal_mutable_struct_fields();
  public:
  const ::googlesql::AnnotationMapProto& struct_fields(int index) const;
  ::googlesql::AnnotationMapProto* add_struct_fields();
  const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>& struct_fields() const;
  // optional .googlesql.AnnotationMapProto array_element = 2 [deprecated = true];
  [[deprecated]]  bool has_array_element() const;
  [[deprecated]]  void clear_array_element() ;
  [[deprecated]] const ::googlesql::AnnotationMapProto& array_element() const;
  [[deprecated]] PROTOBUF_NODISCARD ::googlesql::AnnotationMapProto* release_array_element();
  [[deprecated]] ::googlesql::AnnotationMapProto* mutable_array_element();
  [[deprecated]] void set_allocated_array_element(::googlesql::AnnotationMapProto* value);
  [[deprecated]] void unsafe_arena_set_allocated_array_element(::googlesql::AnnotationMapProto* value);
  [[deprecated]] ::googlesql::AnnotationMapProto* unsafe_arena_release_array_element();

  private:
  const ::googlesql::AnnotationMapProto& _internal_array_element() const;
  ::googlesql::AnnotationMapProto* _internal_mutable_array_element();

  public:
  // optional bool is_null = 4;
  bool has_is_null() const;
  void clear_is_null() ;
  bool is_null() const;
  void set_is_null(bool value);

  private:
  bool _internal_is_null() const;
  void _internal_set_is_null(bool value);

  public:
  // @@protoc_insertion_point(class_scope:googlesql.AnnotationMapProto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 3,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AnnotationMapProto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::googlesql::AnnotationProto > annotations_;
    ::google::protobuf::RepeatedPtrField< ::googlesql::AnnotationMapProto > struct_fields_;
    ::googlesql::AnnotationMapProto* array_element_;
    bool is_null_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fpublic_2fannotation_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AnnotationProto

// optional int64 id = 1;
inline bool AnnotationProto::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AnnotationProto::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t AnnotationProto::id() const {
  // @@protoc_insertion_point(field_get:googlesql.AnnotationProto.id)
  return _internal_id();
}
inline void AnnotationProto::set_id(::int64_t value) {
  _internal_set_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:googlesql.AnnotationProto.id)
}
inline ::int64_t AnnotationProto::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void AnnotationProto::_internal_set_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// optional .googlesql.SimpleValueProto value = 2;
inline bool AnnotationProto::has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.value_ != nullptr);
  return value;
}
inline const ::googlesql::SimpleValueProto& AnnotationProto::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql::SimpleValueProto* p = _impl_.value_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql::SimpleValueProto&>(::googlesql::_SimpleValueProto_default_instance_);
}
inline const ::googlesql::SimpleValueProto& AnnotationProto::value() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.AnnotationProto.value)
  return _internal_value();
}
inline void AnnotationProto::unsafe_arena_set_allocated_value(::googlesql::SimpleValueProto* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.value_);
  }
  _impl_.value_ = reinterpret_cast<::googlesql::SimpleValueProto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql.AnnotationProto.value)
}
inline ::googlesql::SimpleValueProto* AnnotationProto::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::googlesql::SimpleValueProto* released = _impl_.value_;
  _impl_.value_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql::SimpleValueProto* AnnotationProto::unsafe_arena_release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.AnnotationProto.value)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::googlesql::SimpleValueProto* temp = _impl_.value_;
  _impl_.value_ = nullptr;
  return temp;
}
inline ::googlesql::SimpleValueProto* AnnotationProto::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.value_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql::SimpleValueProto>(GetArena());
    _impl_.value_ = reinterpret_cast<::googlesql::SimpleValueProto*>(p);
  }
  return _impl_.value_;
}
inline ::googlesql::SimpleValueProto* AnnotationProto::mutable_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::googlesql::SimpleValueProto* _msg = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:googlesql.AnnotationProto.value)
  return _msg;
}
inline void AnnotationProto::set_allocated_value(::googlesql::SimpleValueProto* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.value_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.value_ = reinterpret_cast<::googlesql::SimpleValueProto*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql.AnnotationProto.value)
}

// -------------------------------------------------------------------

// AnnotationMapProto

// optional bool is_null = 4;
inline bool AnnotationMapProto::has_is_null() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AnnotationMapProto::clear_is_null() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_null_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool AnnotationMapProto::is_null() const {
  // @@protoc_insertion_point(field_get:googlesql.AnnotationMapProto.is_null)
  return _internal_is_null();
}
inline void AnnotationMapProto::set_is_null(bool value) {
  _internal_set_is_null(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:googlesql.AnnotationMapProto.is_null)
}
inline bool AnnotationMapProto::_internal_is_null() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_null_;
}
inline void AnnotationMapProto::_internal_set_is_null(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_null_ = value;
}

// repeated .googlesql.AnnotationProto annotations = 1;
inline int AnnotationMapProto::_internal_annotations_size() const {
  return _internal_annotations().size();
}
inline int AnnotationMapProto::annotations_size() const {
  return _internal_annotations_size();
}
inline void AnnotationMapProto::clear_annotations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.annotations_.Clear();
}
inline ::googlesql::AnnotationProto* AnnotationMapProto::mutable_annotations(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:googlesql.AnnotationMapProto.annotations)
  return _internal_mutable_annotations()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>* AnnotationMapProto::mutable_annotations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:googlesql.AnnotationMapProto.annotations)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_annotations();
}
inline const ::googlesql::AnnotationProto& AnnotationMapProto::annotations(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.AnnotationMapProto.annotations)
  return _internal_annotations().Get(index);
}
inline ::googlesql::AnnotationProto* AnnotationMapProto::add_annotations() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::googlesql::AnnotationProto* _add = _internal_mutable_annotations()->Add();
  // @@protoc_insertion_point(field_add:googlesql.AnnotationMapProto.annotations)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>& AnnotationMapProto::annotations() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:googlesql.AnnotationMapProto.annotations)
  return _internal_annotations();
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>&
AnnotationMapProto::_internal_annotations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.annotations_;
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationProto>*
AnnotationMapProto::_internal_mutable_annotations() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.annotations_;
}

// optional .googlesql.AnnotationMapProto array_element = 2 [deprecated = true];
inline bool AnnotationMapProto::has_array_element() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.array_element_ != nullptr);
  return value;
}
inline void AnnotationMapProto::clear_array_element() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.array_element_ != nullptr) _impl_.array_element_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::googlesql::AnnotationMapProto& AnnotationMapProto::_internal_array_element() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql::AnnotationMapProto* p = _impl_.array_element_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql::AnnotationMapProto&>(::googlesql::_AnnotationMapProto_default_instance_);
}
inline const ::googlesql::AnnotationMapProto& AnnotationMapProto::array_element() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.AnnotationMapProto.array_element)
  return _internal_array_element();
}
inline void AnnotationMapProto::unsafe_arena_set_allocated_array_element(::googlesql::AnnotationMapProto* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.array_element_);
  }
  _impl_.array_element_ = reinterpret_cast<::googlesql::AnnotationMapProto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql.AnnotationMapProto.array_element)
}
inline ::googlesql::AnnotationMapProto* AnnotationMapProto::release_array_element() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::googlesql::AnnotationMapProto* released = _impl_.array_element_;
  _impl_.array_element_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql::AnnotationMapProto* AnnotationMapProto::unsafe_arena_release_array_element() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.AnnotationMapProto.array_element)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::googlesql::AnnotationMapProto* temp = _impl_.array_element_;
  _impl_.array_element_ = nullptr;
  return temp;
}
inline ::googlesql::AnnotationMapProto* AnnotationMapProto::_internal_mutable_array_element() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.array_element_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql::AnnotationMapProto>(GetArena());
    _impl_.array_element_ = reinterpret_cast<::googlesql::AnnotationMapProto*>(p);
  }
  return _impl_.array_element_;
}
inline ::googlesql::AnnotationMapProto* AnnotationMapProto::mutable_array_element() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::googlesql::AnnotationMapProto* _msg = _internal_mutable_array_element();
  // @@protoc_insertion_point(field_mutable:googlesql.AnnotationMapProto.array_element)
  return _msg;
}
inline void AnnotationMapProto::set_allocated_array_element(::googlesql::AnnotationMapProto* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.array_element_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.array_element_ = reinterpret_cast<::googlesql::AnnotationMapProto*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql.AnnotationMapProto.array_element)
}

// repeated .googlesql.AnnotationMapProto struct_fields = 3;
inline int AnnotationMapProto::_internal_struct_fields_size() const {
  return _internal_struct_fields().size();
}
inline int AnnotationMapProto::struct_fields_size() const {
  return _internal_struct_fields_size();
}
inline void AnnotationMapProto::clear_struct_fields() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.struct_fields_.Clear();
}
inline ::googlesql::AnnotationMapProto* AnnotationMapProto::mutable_struct_fields(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:googlesql.AnnotationMapProto.struct_fields)
  return _internal_mutable_struct_fields()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>* AnnotationMapProto::mutable_struct_fields()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:googlesql.AnnotationMapProto.struct_fields)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_struct_fields();
}
inline const ::googlesql::AnnotationMapProto& AnnotationMapProto::struct_fields(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.AnnotationMapProto.struct_fields)
  return _internal_struct_fields().Get(index);
}
inline ::googlesql::AnnotationMapProto* AnnotationMapProto::add_struct_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::googlesql::AnnotationMapProto* _add = _internal_mutable_struct_fields()->Add();
  // @@protoc_insertion_point(field_add:googlesql.AnnotationMapProto.struct_fields)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>& AnnotationMapProto::struct_fields() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:googlesql.AnnotationMapProto.struct_fields)
  return _internal_struct_fields();
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>&
AnnotationMapProto::_internal_struct_fields() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.struct_fields_;
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::AnnotationMapProto>*
AnnotationMapProto::_internal_mutable_struct_fields() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.struct_fields_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2fannotation_2eproto_2epb_2eh
