// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/collation.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/collation.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {

inline constexpr CollationProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        child_list_{},
        collation_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CollationProto::CollationProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CollationProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CollationProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CollationProtoDefaultTypeInternal() {}
  union {
    CollationProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CollationProtoDefaultTypeInternal _CollationProto_default_instance_;
}  // namespace googlesql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_googlesql_2fpublic_2fcollation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2fcollation_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2fcollation_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::googlesql::CollationProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::CollationProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::CollationProto, _impl_.collation_name_),
        PROTOBUF_FIELD_OFFSET(::googlesql::CollationProto, _impl_.child_list_),
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::googlesql::CollationProto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::_CollationProto_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2fcollation_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n googlesql/public/collation.proto\022\tgoog"
    "lesql\"W\n\016CollationProto\022\026\n\016collation_nam"
    "e\030\001 \001(\t\022-\n\nchild_list\030\002 \003(\0132\031.googlesql."
    "CollationProtoB*\n\024com.google.googlesqlB\022"
    "GoogleSQLCollation"
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2fcollation_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2fcollation_2eproto = {
    false,
    false,
    178,
    descriptor_table_protodef_googlesql_2fpublic_2fcollation_2eproto,
    "googlesql/public/collation.proto",
    &descriptor_table_googlesql_2fpublic_2fcollation_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2fcollation_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2fcollation_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2fcollation_2eproto,
};
namespace googlesql {
// ===================================================================

class CollationProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CollationProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CollationProto, _impl_._has_bits_);
};

CollationProto::CollationProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.CollationProto)
}
inline PROTOBUF_NDEBUG_INLINE CollationProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::CollationProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        child_list_{visibility, arena, from.child_list_},
        collation_name_(arena, from.collation_name_) {}

CollationProto::CollationProto(
    ::google::protobuf::Arena* arena,
    const CollationProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CollationProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:googlesql.CollationProto)
}
inline PROTOBUF_NDEBUG_INLINE CollationProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        child_list_{visibility, arena},
        collation_name_(arena) {}

inline void CollationProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CollationProto::~CollationProto() {
  // @@protoc_insertion_point(destructor:googlesql.CollationProto)
  SharedDtor(*this);
}
inline void CollationProto::SharedDtor(MessageLite& self) {
  CollationProto& this_ = static_cast<CollationProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.collation_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CollationProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CollationProto(arena);
}
constexpr auto CollationProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CollationProto, _impl_.child_list_) +
          decltype(CollationProto::_impl_.child_list_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(CollationProto), alignof(CollationProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CollationProto::PlacementNew_,
                                 sizeof(CollationProto),
                                 alignof(CollationProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CollationProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CollationProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CollationProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CollationProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CollationProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CollationProto>(), &CollationProto::ByteSizeLong,
            &CollationProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CollationProto, _impl_._cached_size_),
        false,
    },
    &CollationProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fcollation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CollationProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 47, 2> CollationProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CollationProto, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::CollationProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .googlesql.CollationProto child_list = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CollationProto, _impl_.child_list_)}},
    // optional string collation_name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CollationProto, _impl_.collation_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string collation_name = 1;
    {PROTOBUF_FIELD_OFFSET(CollationProto, _impl_.collation_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated .googlesql.CollationProto child_list = 2;
    {PROTOBUF_FIELD_OFFSET(CollationProto, _impl_.child_list_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::CollationProto>()},
  }}, {{
    "\30\16\0\0\0\0\0\0"
    "googlesql.CollationProto"
    "collation_name"
  }},
};

PROTOBUF_NOINLINE void CollationProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.CollationProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.child_list_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.collation_name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CollationProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CollationProto& this_ = static_cast<const CollationProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CollationProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CollationProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.CollationProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string collation_name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_collation_name();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.CollationProto.collation_name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated .googlesql.CollationProto child_list = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_child_list_size());
               i < n; i++) {
            const auto& repfield = this_._internal_child_list().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.CollationProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CollationProto::ByteSizeLong(const MessageLite& base) {
          const CollationProto& this_ = static_cast<const CollationProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CollationProto::ByteSizeLong() const {
          const CollationProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.CollationProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.CollationProto child_list = 2;
            {
              total_size += 1UL * this_._internal_child_list_size();
              for (const auto& msg : this_._internal_child_list()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // optional string collation_name = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_collation_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CollationProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CollationProto*>(&to_msg);
  auto& from = static_cast<const CollationProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.CollationProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_child_list()->MergeFrom(
      from._internal_child_list());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_internal_set_collation_name(from._internal_collation_name());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CollationProto::CopyFrom(const CollationProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.CollationProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CollationProto::InternalSwap(CollationProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.child_list_.InternalSwap(&other->_impl_.child_list_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.collation_name_, &other->_impl_.collation_name_, arena);
}

::google::protobuf::Metadata CollationProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2fcollation_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
