// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/error_location.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/error_location.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {

inline constexpr ErrorLocation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        error_source_{},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        input_start_line_offset_{0},
        input_start_column_offset_{0},
        line_{1},
        column_{1} {}

template <typename>
PROTOBUF_CONSTEXPR ErrorLocation::ErrorLocation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ErrorLocationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorLocationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorLocationDefaultTypeInternal() {}
  union {
    ErrorLocation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorLocationDefaultTypeInternal _ErrorLocation_default_instance_;

inline constexpr ErrorSource::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_message_caret_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_location_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ErrorSource::ErrorSource(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ErrorSourceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorSourceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorSourceDefaultTypeInternal() {}
  union {
    ErrorSource _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorSourceDefaultTypeInternal _ErrorSource_default_instance_;
}  // namespace googlesql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_googlesql_2fpublic_2ferror_5flocation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2ferror_5flocation_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _impl_.line_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _impl_.column_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _impl_.input_start_line_offset_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _impl_.input_start_column_offset_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorLocation, _impl_.error_source_),
        3,
        4,
        0,
        1,
        2,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorSource, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorSource, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorSource, _impl_.error_message_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorSource, _impl_.error_message_caret_string_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ErrorSource, _impl_.error_location_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::googlesql::ErrorLocation)},
        {20, 31, -1, sizeof(::googlesql::ErrorSource)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::_ErrorLocation_default_instance_._instance,
    &::googlesql::_ErrorSource_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2ferror_5flocation_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n%googlesql/public/error_location.proto\022"
    "\tgooglesql\"\267\001\n\rErrorLocation\022\017\n\004line\030\001 \001"
    "(\005:\0011\022\021\n\006column\030\002 \001(\005:\0011\022\020\n\010filename\030\003 \001"
    "(\t\022\037\n\027input_start_line_offset\030\005 \001(\005\022!\n\031i"
    "nput_start_column_offset\030\006 \001(\005\022,\n\014error_"
    "source\030\004 \003(\0132\026.googlesql.ErrorSource\"z\n\013"
    "ErrorSource\022\025\n\rerror_message\030\001 \001(\t\022\"\n\032er"
    "ror_message_caret_string\030\002 \001(\t\0220\n\016error_"
    "location\030\003 \001(\0132\030.googlesql.ErrorLocation"
    "B\026\n\024com.google.googlesql"
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto = {
    false,
    false,
    384,
    descriptor_table_protodef_googlesql_2fpublic_2ferror_5flocation_2eproto,
    "googlesql/public/error_location.proto",
    &descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2ferror_5flocation_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2ferror_5flocation_2eproto,
};
namespace googlesql {
// ===================================================================

class ErrorLocation::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ErrorLocation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_._has_bits_);
};

ErrorLocation::ErrorLocation(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.ErrorLocation)
}
inline PROTOBUF_NDEBUG_INLINE ErrorLocation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::ErrorLocation& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        error_source_{visibility, arena, from.error_source_},
        filename_(arena, from.filename_) {}

ErrorLocation::ErrorLocation(
    ::google::protobuf::Arena* arena,
    const ErrorLocation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ErrorLocation* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, input_start_line_offset_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, input_start_line_offset_),
           offsetof(Impl_, column_) -
               offsetof(Impl_, input_start_line_offset_) +
               sizeof(Impl_::column_));

  // @@protoc_insertion_point(copy_constructor:googlesql.ErrorLocation)
}
inline PROTOBUF_NDEBUG_INLINE ErrorLocation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        error_source_{visibility, arena},
        filename_(arena),
        line_{1},
        column_{1} {}

inline void ErrorLocation::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, input_start_line_offset_),
           0,
           offsetof(Impl_, input_start_column_offset_) -
               offsetof(Impl_, input_start_line_offset_) +
               sizeof(Impl_::input_start_column_offset_));
}
ErrorLocation::~ErrorLocation() {
  // @@protoc_insertion_point(destructor:googlesql.ErrorLocation)
  SharedDtor(*this);
}
inline void ErrorLocation::SharedDtor(MessageLite& self) {
  ErrorLocation& this_ = static_cast<ErrorLocation&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ErrorLocation::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ErrorLocation(arena);
}
constexpr auto ErrorLocation::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.error_source_) +
          decltype(ErrorLocation::_impl_.error_source_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ErrorLocation), alignof(ErrorLocation), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ErrorLocation::PlacementNew_,
                                 sizeof(ErrorLocation),
                                 alignof(ErrorLocation));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ErrorLocation::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ErrorLocation_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ErrorLocation::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ErrorLocation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ErrorLocation::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ErrorLocation>(), &ErrorLocation::ByteSizeLong,
            &ErrorLocation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_._cached_size_),
        false,
    },
    &ErrorLocation::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ErrorLocation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 40, 2> ErrorLocation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::ErrorLocation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 line = 1 [default = 1];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ErrorLocation, _impl_.line_), 3>(),
     {8, 3, 0, PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.line_)}},
    // optional int32 column = 2 [default = 1];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ErrorLocation, _impl_.column_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.column_)}},
    // optional string filename = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.filename_)}},
    // repeated .googlesql.ErrorSource error_source = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.error_source_)}},
    // optional int32 input_start_line_offset = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ErrorLocation, _impl_.input_start_line_offset_), 1>(),
     {40, 1, 0, PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.input_start_line_offset_)}},
    // optional int32 input_start_column_offset = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ErrorLocation, _impl_.input_start_column_offset_), 2>(),
     {48, 2, 0, PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.input_start_column_offset_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 line = 1 [default = 1];
    {PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.line_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 column = 2 [default = 1];
    {PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.column_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string filename = 3;
    {PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated .googlesql.ErrorSource error_source = 4;
    {PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.error_source_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int32 input_start_line_offset = 5;
    {PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.input_start_line_offset_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 input_start_column_offset = 6;
    {PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.input_start_column_offset_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::ErrorSource>()},
  }}, {{
    "\27\0\0\10\0\0\0\0"
    "googlesql.ErrorLocation"
    "filename"
  }},
};

PROTOBUF_NOINLINE void ErrorLocation::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.ErrorLocation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_source_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.filename_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000001eu) {
    ::memset(&_impl_.input_start_line_offset_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.input_start_column_offset_) -
        reinterpret_cast<char*>(&_impl_.input_start_line_offset_)) + sizeof(_impl_.input_start_column_offset_));
    _impl_.line_ = 1;
    _impl_.column_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ErrorLocation::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ErrorLocation& this_ = static_cast<const ErrorLocation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ErrorLocation::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ErrorLocation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.ErrorLocation)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 line = 1 [default = 1];
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_line(), target);
          }

          // optional int32 column = 2 [default = 1];
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_column(), target);
          }

          // optional string filename = 3;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_filename();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.ErrorLocation.filename");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // repeated .googlesql.ErrorSource error_source = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_error_source_size());
               i < n; i++) {
            const auto& repfield = this_._internal_error_source().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // optional int32 input_start_line_offset = 5;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<5>(
                    stream, this_._internal_input_start_line_offset(), target);
          }

          // optional int32 input_start_column_offset = 6;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_input_start_column_offset(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.ErrorLocation)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ErrorLocation::ByteSizeLong(const MessageLite& base) {
          const ErrorLocation& this_ = static_cast<const ErrorLocation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ErrorLocation::ByteSizeLong() const {
          const ErrorLocation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.ErrorLocation)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.ErrorSource error_source = 4;
            {
              total_size += 1UL * this_._internal_error_source_size();
              for (const auto& msg : this_._internal_error_source()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000001fu) {
            // optional string filename = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filename());
            }
            // optional int32 input_start_line_offset = 5;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_input_start_line_offset());
            }
            // optional int32 input_start_column_offset = 6;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_input_start_column_offset());
            }
            // optional int32 line = 1 [default = 1];
            if (cached_has_bits & 0x00000008u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_line());
            }
            // optional int32 column = 2 [default = 1];
            if (cached_has_bits & 0x00000010u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_column());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ErrorLocation::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ErrorLocation*>(&to_msg);
  auto& from = static_cast<const ErrorLocation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.ErrorLocation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_error_source()->MergeFrom(
      from._internal_error_source());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_filename(from._internal_filename());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.input_start_line_offset_ = from._impl_.input_start_line_offset_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.input_start_column_offset_ = from._impl_.input_start_column_offset_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.line_ = from._impl_.line_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.column_ = from._impl_.column_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorLocation::CopyFrom(const ErrorLocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.ErrorLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ErrorLocation::InternalSwap(ErrorLocation* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.error_source_.InternalSwap(&other->_impl_.error_source_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.column_)
      + sizeof(ErrorLocation::_impl_.column_)
      - PROTOBUF_FIELD_OFFSET(ErrorLocation, _impl_.input_start_line_offset_)>(
          reinterpret_cast<char*>(&_impl_.input_start_line_offset_),
          reinterpret_cast<char*>(&other->_impl_.input_start_line_offset_));
}

::google::protobuf::Metadata ErrorLocation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ErrorSource::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ErrorSource>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_._has_bits_);
};

ErrorSource::ErrorSource(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.ErrorSource)
}
inline PROTOBUF_NDEBUG_INLINE ErrorSource::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::ErrorSource& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        error_message_(arena, from.error_message_),
        error_message_caret_string_(arena, from.error_message_caret_string_) {}

ErrorSource::ErrorSource(
    ::google::protobuf::Arena* arena,
    const ErrorSource& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ErrorSource* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.error_location_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::ErrorLocation>(
                              arena, *from._impl_.error_location_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:googlesql.ErrorSource)
}
inline PROTOBUF_NDEBUG_INLINE ErrorSource::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        error_message_(arena),
        error_message_caret_string_(arena) {}

inline void ErrorSource::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_location_ = {};
}
ErrorSource::~ErrorSource() {
  // @@protoc_insertion_point(destructor:googlesql.ErrorSource)
  SharedDtor(*this);
}
inline void ErrorSource::SharedDtor(MessageLite& self) {
  ErrorSource& this_ = static_cast<ErrorSource&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_message_.Destroy();
  this_._impl_.error_message_caret_string_.Destroy();
  delete this_._impl_.error_location_;
  this_._impl_.~Impl_();
}

inline void* ErrorSource::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ErrorSource(arena);
}
constexpr auto ErrorSource::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ErrorSource),
                                            alignof(ErrorSource));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ErrorSource::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ErrorSource_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ErrorSource::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ErrorSource>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ErrorSource::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ErrorSource>(), &ErrorSource::ByteSizeLong,
            &ErrorSource::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_._cached_size_),
        false,
    },
    &ErrorSource::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ErrorSource::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 69, 2> ErrorSource::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::ErrorSource>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string error_message = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_.error_message_)}},
    // optional string error_message_caret_string = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_.error_message_caret_string_)}},
    // optional .googlesql.ErrorLocation error_location = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_.error_location_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string error_message = 1;
    {PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_.error_message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string error_message_caret_string = 2;
    {PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_.error_message_caret_string_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional .googlesql.ErrorLocation error_location = 3;
    {PROTOBUF_FIELD_OFFSET(ErrorSource, _impl_.error_location_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::ErrorLocation>()},
  }}, {{
    "\25\15\32\0\0\0\0\0"
    "googlesql.ErrorSource"
    "error_message"
    "error_message_caret_string"
  }},
};

PROTOBUF_NOINLINE void ErrorSource::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.ErrorSource)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.error_message_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.error_message_caret_string_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.error_location_ != nullptr);
      _impl_.error_location_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ErrorSource::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ErrorSource& this_ = static_cast<const ErrorSource&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ErrorSource::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ErrorSource& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.ErrorSource)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string error_message = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_error_message();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.ErrorSource.error_message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional string error_message_caret_string = 2;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_error_message_caret_string();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.ErrorSource.error_message_caret_string");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // optional .googlesql.ErrorLocation error_location = 3;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.error_location_, this_._impl_.error_location_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.ErrorSource)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ErrorSource::ByteSizeLong(const MessageLite& base) {
          const ErrorSource& this_ = static_cast<const ErrorSource&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ErrorSource::ByteSizeLong() const {
          const ErrorSource& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.ErrorSource)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // optional string error_message = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error_message());
            }
            // optional string error_message_caret_string = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error_message_caret_string());
            }
            // optional .googlesql.ErrorLocation error_location = 3;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.error_location_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ErrorSource::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ErrorSource*>(&to_msg);
  auto& from = static_cast<const ErrorSource&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.ErrorSource)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_error_message(from._internal_error_message());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_error_message_caret_string(from._internal_error_message_caret_string());
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.error_location_ != nullptr);
      if (_this->_impl_.error_location_ == nullptr) {
        _this->_impl_.error_location_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::ErrorLocation>(arena, *from._impl_.error_location_);
      } else {
        _this->_impl_.error_location_->MergeFrom(*from._impl_.error_location_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorSource::CopyFrom(const ErrorSource& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.ErrorSource)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ErrorSource::InternalSwap(ErrorSource* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_caret_string_, &other->_impl_.error_message_caret_string_, arena);
  swap(_impl_.error_location_, other->_impl_.error_location_);
}

::google::protobuf::Metadata ErrorSource::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
