// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/type_annotation.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/type_annotation.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {
namespace storage {
}  // namespace storage
}  // namespace googlesql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_googlesql_2fpublic_2ftype_5fannotation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2ftype_5fannotation_2eproto = nullptr;
const ::uint32_t TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_googlesql_2fpublic_2ftype_5fannotation_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n&googlesql/public/type_annotation.proto"
    "\022\021googlesql.storage\032,googlesql/public/pr"
    "oto/type_annotation.protoB\"\n\024com.google."
    "googlesql\242\002\tGOOGLESQL"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto = {
    false,
    false,
    141,
    descriptor_table_protodef_googlesql_2fpublic_2ftype_5fannotation_2eproto,
    "googlesql/public/type_annotation.proto",
    &descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto_once,
    descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2ftype_5fannotation_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2ftype_5fannotation_2eproto,
};
namespace googlesql {
namespace storage {
// @@protoc_insertion_point(namespace_scope)
}  // namespace storage
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
