// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/type_modifiers.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2ftype_5fmodifiers_2eproto_2epb_2eh
#define googlesql_2fpublic_2ftype_5fmodifiers_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "googlesql/public/collation.pb.h"
#include "googlesql/public/type_parameters.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2ftype_5fmodifiers_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2ftype_5fmodifiers_2eproto;
namespace googlesql {
class TypeModifiersProto;
struct TypeModifiersProtoDefaultTypeInternal;
extern TypeModifiersProtoDefaultTypeInternal _TypeModifiersProto_default_instance_;
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {

// ===================================================================


// -------------------------------------------------------------------

class TypeModifiersProto final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql.TypeModifiersProto) */ {
 public:
  inline TypeModifiersProto() : TypeModifiersProto(nullptr) {}
  ~TypeModifiersProto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TypeModifiersProto* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TypeModifiersProto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TypeModifiersProto(
      ::google::protobuf::internal::ConstantInitialized);

  inline TypeModifiersProto(const TypeModifiersProto& from) : TypeModifiersProto(nullptr, from) {}
  inline TypeModifiersProto(TypeModifiersProto&& from) noexcept
      : TypeModifiersProto(nullptr, std::move(from)) {}
  inline TypeModifiersProto& operator=(const TypeModifiersProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TypeModifiersProto& operator=(TypeModifiersProto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TypeModifiersProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TypeModifiersProto* internal_default_instance() {
    return reinterpret_cast<const TypeModifiersProto*>(
        &_TypeModifiersProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TypeModifiersProto& a, TypeModifiersProto& b) { a.Swap(&b); }
  inline void Swap(TypeModifiersProto* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TypeModifiersProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TypeModifiersProto* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TypeModifiersProto>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TypeModifiersProto& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TypeModifiersProto& from) { TypeModifiersProto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TypeModifiersProto* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.TypeModifiersProto"; }

 protected:
  explicit TypeModifiersProto(::google::protobuf::Arena* arena);
  TypeModifiersProto(::google::protobuf::Arena* arena, const TypeModifiersProto& from);
  TypeModifiersProto(::google::protobuf::Arena* arena, TypeModifiersProto&& from) noexcept
      : TypeModifiersProto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeParametersFieldNumber = 1,
    kCollationFieldNumber = 2,
  };
  // optional .googlesql.TypeParametersProto type_parameters = 1;
  bool has_type_parameters() const;
  void clear_type_parameters() ;
  const ::googlesql::TypeParametersProto& type_parameters() const;
  PROTOBUF_NODISCARD ::googlesql::TypeParametersProto* release_type_parameters();
  ::googlesql::TypeParametersProto* mutable_type_parameters();
  void set_allocated_type_parameters(::googlesql::TypeParametersProto* value);
  void unsafe_arena_set_allocated_type_parameters(::googlesql::TypeParametersProto* value);
  ::googlesql::TypeParametersProto* unsafe_arena_release_type_parameters();

  private:
  const ::googlesql::TypeParametersProto& _internal_type_parameters() const;
  ::googlesql::TypeParametersProto* _internal_mutable_type_parameters();

  public:
  // optional .googlesql.CollationProto collation = 2;
  bool has_collation() const;
  void clear_collation() ;
  const ::googlesql::CollationProto& collation() const;
  PROTOBUF_NODISCARD ::googlesql::CollationProto* release_collation();
  ::googlesql::CollationProto* mutable_collation();
  void set_allocated_collation(::googlesql::CollationProto* value);
  void unsafe_arena_set_allocated_collation(::googlesql::CollationProto* value);
  ::googlesql::CollationProto* unsafe_arena_release_collation();

  private:
  const ::googlesql::CollationProto& _internal_collation() const;
  ::googlesql::CollationProto* _internal_mutable_collation();

  public:
  // @@protoc_insertion_point(class_scope:googlesql.TypeModifiersProto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TypeModifiersProto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::googlesql::TypeParametersProto* type_parameters_;
    ::googlesql::CollationProto* collation_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TypeModifiersProto

// optional .googlesql.TypeParametersProto type_parameters = 1;
inline bool TypeModifiersProto::has_type_parameters() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.type_parameters_ != nullptr);
  return value;
}
inline const ::googlesql::TypeParametersProto& TypeModifiersProto::_internal_type_parameters() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql::TypeParametersProto* p = _impl_.type_parameters_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql::TypeParametersProto&>(::googlesql::_TypeParametersProto_default_instance_);
}
inline const ::googlesql::TypeParametersProto& TypeModifiersProto::type_parameters() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.TypeModifiersProto.type_parameters)
  return _internal_type_parameters();
}
inline void TypeModifiersProto::unsafe_arena_set_allocated_type_parameters(::googlesql::TypeParametersProto* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.type_parameters_);
  }
  _impl_.type_parameters_ = reinterpret_cast<::googlesql::TypeParametersProto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql.TypeModifiersProto.type_parameters)
}
inline ::googlesql::TypeParametersProto* TypeModifiersProto::release_type_parameters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::googlesql::TypeParametersProto* released = _impl_.type_parameters_;
  _impl_.type_parameters_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql::TypeParametersProto* TypeModifiersProto::unsafe_arena_release_type_parameters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.TypeModifiersProto.type_parameters)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::googlesql::TypeParametersProto* temp = _impl_.type_parameters_;
  _impl_.type_parameters_ = nullptr;
  return temp;
}
inline ::googlesql::TypeParametersProto* TypeModifiersProto::_internal_mutable_type_parameters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.type_parameters_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql::TypeParametersProto>(GetArena());
    _impl_.type_parameters_ = reinterpret_cast<::googlesql::TypeParametersProto*>(p);
  }
  return _impl_.type_parameters_;
}
inline ::googlesql::TypeParametersProto* TypeModifiersProto::mutable_type_parameters() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::googlesql::TypeParametersProto* _msg = _internal_mutable_type_parameters();
  // @@protoc_insertion_point(field_mutable:googlesql.TypeModifiersProto.type_parameters)
  return _msg;
}
inline void TypeModifiersProto::set_allocated_type_parameters(::googlesql::TypeParametersProto* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.type_parameters_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.type_parameters_ = reinterpret_cast<::googlesql::TypeParametersProto*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql.TypeModifiersProto.type_parameters)
}

// optional .googlesql.CollationProto collation = 2;
inline bool TypeModifiersProto::has_collation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.collation_ != nullptr);
  return value;
}
inline const ::googlesql::CollationProto& TypeModifiersProto::_internal_collation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql::CollationProto* p = _impl_.collation_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql::CollationProto&>(::googlesql::_CollationProto_default_instance_);
}
inline const ::googlesql::CollationProto& TypeModifiersProto::collation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.TypeModifiersProto.collation)
  return _internal_collation();
}
inline void TypeModifiersProto::unsafe_arena_set_allocated_collation(::googlesql::CollationProto* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.collation_);
  }
  _impl_.collation_ = reinterpret_cast<::googlesql::CollationProto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql.TypeModifiersProto.collation)
}
inline ::googlesql::CollationProto* TypeModifiersProto::release_collation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::googlesql::CollationProto* released = _impl_.collation_;
  _impl_.collation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql::CollationProto* TypeModifiersProto::unsafe_arena_release_collation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.TypeModifiersProto.collation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::googlesql::CollationProto* temp = _impl_.collation_;
  _impl_.collation_ = nullptr;
  return temp;
}
inline ::googlesql::CollationProto* TypeModifiersProto::_internal_mutable_collation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.collation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql::CollationProto>(GetArena());
    _impl_.collation_ = reinterpret_cast<::googlesql::CollationProto*>(p);
  }
  return _impl_.collation_;
}
inline ::googlesql::CollationProto* TypeModifiersProto::mutable_collation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::googlesql::CollationProto* _msg = _internal_mutable_collation();
  // @@protoc_insertion_point(field_mutable:googlesql.TypeModifiersProto.collation)
  return _msg;
}
inline void TypeModifiersProto::set_allocated_collation(::googlesql::CollationProto* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.collation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.collation_ = reinterpret_cast<::googlesql::CollationProto*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql.TypeModifiersProto.collation)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2ftype_5fmodifiers_2eproto_2epb_2eh
