// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/array_find_mode.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto_2epb_2eh
#define googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "googlesql/public/type.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto;
namespace googlesql {
namespace functions {
class ArrayFindEnums;
struct ArrayFindEnumsDefaultTypeInternal;
extern ArrayFindEnumsDefaultTypeInternal _ArrayFindEnums_default_instance_;
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {
namespace functions {
enum ArrayFindEnums_ArrayFindMode : int {
  ArrayFindEnums_ArrayFindMode_ARRAY_FIND_MODE_INVALID = 0,
  ArrayFindEnums_ArrayFindMode_FIRST = 1,
  ArrayFindEnums_ArrayFindMode_LAST = 2,
};

bool ArrayFindEnums_ArrayFindMode_IsValid(int value);
extern const uint32_t ArrayFindEnums_ArrayFindMode_internal_data_[];
constexpr ArrayFindEnums_ArrayFindMode ArrayFindEnums_ArrayFindMode_ArrayFindMode_MIN = static_cast<ArrayFindEnums_ArrayFindMode>(0);
constexpr ArrayFindEnums_ArrayFindMode ArrayFindEnums_ArrayFindMode_ArrayFindMode_MAX = static_cast<ArrayFindEnums_ArrayFindMode>(2);
constexpr int ArrayFindEnums_ArrayFindMode_ArrayFindMode_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
ArrayFindEnums_ArrayFindMode_descriptor();
template <typename T>
const std::string& ArrayFindEnums_ArrayFindMode_Name(T value) {
  static_assert(std::is_same<T, ArrayFindEnums_ArrayFindMode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ArrayFindMode_Name().");
  return ArrayFindEnums_ArrayFindMode_Name(static_cast<ArrayFindEnums_ArrayFindMode>(value));
}
template <>
inline const std::string& ArrayFindEnums_ArrayFindMode_Name(ArrayFindEnums_ArrayFindMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ArrayFindEnums_ArrayFindMode_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool ArrayFindEnums_ArrayFindMode_Parse(absl::string_view name, ArrayFindEnums_ArrayFindMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ArrayFindEnums_ArrayFindMode>(
      ArrayFindEnums_ArrayFindMode_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class ArrayFindEnums final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:googlesql.functions.ArrayFindEnums) */ {
 public:
  inline ArrayFindEnums() : ArrayFindEnums(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ArrayFindEnums* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ArrayFindEnums));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ArrayFindEnums(
      ::google::protobuf::internal::ConstantInitialized);

  inline ArrayFindEnums(const ArrayFindEnums& from) : ArrayFindEnums(nullptr, from) {}
  inline ArrayFindEnums(ArrayFindEnums&& from) noexcept
      : ArrayFindEnums(nullptr, std::move(from)) {}
  inline ArrayFindEnums& operator=(const ArrayFindEnums& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArrayFindEnums& operator=(ArrayFindEnums&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ArrayFindEnums& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArrayFindEnums* internal_default_instance() {
    return reinterpret_cast<const ArrayFindEnums*>(
        &_ArrayFindEnums_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ArrayFindEnums& a, ArrayFindEnums& b) { a.Swap(&b); }
  inline void Swap(ArrayFindEnums* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArrayFindEnums* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ArrayFindEnums* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<ArrayFindEnums>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ArrayFindEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ArrayFindEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.functions.ArrayFindEnums"; }

 protected:
  explicit ArrayFindEnums(::google::protobuf::Arena* arena);
  ArrayFindEnums(::google::protobuf::Arena* arena, const ArrayFindEnums& from);
  ArrayFindEnums(::google::protobuf::Arena* arena, ArrayFindEnums&& from) noexcept
      : ArrayFindEnums(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ArrayFindMode = ArrayFindEnums_ArrayFindMode;
  static constexpr ArrayFindMode ARRAY_FIND_MODE_INVALID = ArrayFindEnums_ArrayFindMode_ARRAY_FIND_MODE_INVALID;
  static constexpr ArrayFindMode FIRST = ArrayFindEnums_ArrayFindMode_FIRST;
  static constexpr ArrayFindMode LAST = ArrayFindEnums_ArrayFindMode_LAST;
  static inline bool ArrayFindMode_IsValid(int value) {
    return ArrayFindEnums_ArrayFindMode_IsValid(value);
  }
  static constexpr ArrayFindMode ArrayFindMode_MIN = ArrayFindEnums_ArrayFindMode_ArrayFindMode_MIN;
  static constexpr ArrayFindMode ArrayFindMode_MAX = ArrayFindEnums_ArrayFindMode_ArrayFindMode_MAX;
  static constexpr int ArrayFindMode_ARRAYSIZE = ArrayFindEnums_ArrayFindMode_ArrayFindMode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* ArrayFindMode_descriptor() {
    return ArrayFindEnums_ArrayFindMode_descriptor();
  }
  template <typename T>
  static inline const std::string& ArrayFindMode_Name(T value) {
    return ArrayFindEnums_ArrayFindMode_Name(value);
  }
  static inline bool ArrayFindMode_Parse(absl::string_view name, ArrayFindMode* value) {
    return ArrayFindEnums_ArrayFindMode_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:googlesql.functions.ArrayFindEnums)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ArrayFindEnums& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ArrayFindEnums

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::googlesql::functions::ArrayFindEnums_ArrayFindMode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::functions::ArrayFindEnums_ArrayFindMode>() {
  return ::googlesql::functions::ArrayFindEnums_ArrayFindMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto_2epb_2eh
