// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/bitwise_agg_mode.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/functions/bitwise_agg_mode.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {
namespace functions {
              template <typename>
PROTOBUF_CONSTEXPR BitwiseAggEnums::BitwiseAggEnums(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct BitwiseAggEnumsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BitwiseAggEnumsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BitwiseAggEnumsDefaultTypeInternal() {}
  union {
    BitwiseAggEnums _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BitwiseAggEnumsDefaultTypeInternal _BitwiseAggEnums_default_instance_;
}  // namespace functions
}  // namespace googlesql
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::BitwiseAggEnums, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::googlesql::functions::BitwiseAggEnums)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::functions::_BitwiseAggEnums_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n1googlesql/public/functions/bitwise_agg"
    "_mode.proto\022\023googlesql.functions\032\033google"
    "sql/public/type.proto\"z\n\017BitwiseAggEnums"
    "\"g\n\016BitwiseAggMode\022&\n\030BITWISE_AGG_MODE_I"
    "NVALID\020\000\032\010\262\362\260\222\016\002\010\001\022\n\n\006STRICT\020\001\022\007\n\003PAD\020\002\032"
    "\030\262\320\257\372\r\022\n\020BITWISE_AGG_MODEB9\n\036com.google."
    "googlesql.functionsB\027GoogleSQLBitwiseAgg"
    "Mode"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fpublic_2ftype_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto = {
    false,
    false,
    284,
    descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto,
    "googlesql/public/functions/bitwise_agg_mode.proto",
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto_once,
    descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto,
};
namespace googlesql {
namespace functions {
const ::google::protobuf::EnumDescriptor* BitwiseAggEnums_BitwiseAggMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto);
  return file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t BitwiseAggEnums_BitwiseAggMode_internal_data_[] = {
    196608u, 0u, };
bool BitwiseAggEnums_BitwiseAggMode_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr BitwiseAggEnums_BitwiseAggMode BitwiseAggEnums::BITWISE_AGG_MODE_INVALID;
constexpr BitwiseAggEnums_BitwiseAggMode BitwiseAggEnums::STRICT;
constexpr BitwiseAggEnums_BitwiseAggMode BitwiseAggEnums::PAD;
constexpr BitwiseAggEnums_BitwiseAggMode BitwiseAggEnums::BitwiseAggMode_MIN;
constexpr BitwiseAggEnums_BitwiseAggMode BitwiseAggEnums::BitwiseAggMode_MAX;
constexpr int BitwiseAggEnums::BitwiseAggMode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class BitwiseAggEnums::_Internal {
 public:
};

BitwiseAggEnums::BitwiseAggEnums(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:googlesql.functions.BitwiseAggEnums)
}
BitwiseAggEnums::BitwiseAggEnums(
    ::google::protobuf::Arena* arena,
    const BitwiseAggEnums& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BitwiseAggEnums* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:googlesql.functions.BitwiseAggEnums)
}

inline void* BitwiseAggEnums::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BitwiseAggEnums(arena);
}
constexpr auto BitwiseAggEnums::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BitwiseAggEnums),
                                            alignof(BitwiseAggEnums));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BitwiseAggEnums::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BitwiseAggEnums_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BitwiseAggEnums::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<BitwiseAggEnums>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BitwiseAggEnums::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<BitwiseAggEnums>(), &BitwiseAggEnums::ByteSizeLong,
            &BitwiseAggEnums::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BitwiseAggEnums, _impl_._cached_size_),
        false,
    },
    &BitwiseAggEnums::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BitwiseAggEnums::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> BitwiseAggEnums::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::functions::BitwiseAggEnums>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata BitwiseAggEnums::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
