// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/datetime.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2ffunctions_2fdatetime_2eproto_2epb_2eh
#define googlesql_2fpublic_2ffunctions_2fdatetime_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {
namespace functions {
enum DateTimestampPart : int {
  __DateTimePart__switch_must_have_a_default__ = -1,
  YEAR = 1,
  MONTH = 2,
  DAY = 3,
  DAYOFWEEK = 4,
  DAYOFYEAR = 5,
  QUARTER = 6,
  HOUR = 7,
  MINUTE = 8,
  SECOND = 9,
  MILLISECOND = 10,
  MICROSECOND = 11,
  NANOSECOND = 12,
  PICOSECOND = 25,
  DATE = 13,
  WEEK = 14,
  DATETIME = 15,
  TIME = 16,
  ISOYEAR = 17,
  ISOWEEK = 18,
  WEEK_MONDAY = 19,
  WEEK_TUESDAY = 20,
  WEEK_WEDNESDAY = 21,
  WEEK_THURSDAY = 22,
  WEEK_FRIDAY = 23,
  WEEK_SATURDAY = 24,
};

bool DateTimestampPart_IsValid(int value);
extern const uint32_t DateTimestampPart_internal_data_[];
constexpr DateTimestampPart DateTimestampPart_MIN = static_cast<DateTimestampPart>(-1);
constexpr DateTimestampPart DateTimestampPart_MAX = static_cast<DateTimestampPart>(25);
constexpr int DateTimestampPart_ARRAYSIZE = 25 + 1;
const ::google::protobuf::EnumDescriptor*
DateTimestampPart_descriptor();
template <typename T>
const std::string& DateTimestampPart_Name(T value) {
  static_assert(std::is_same<T, DateTimestampPart>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DateTimestampPart_Name().");
  return DateTimestampPart_Name(static_cast<DateTimestampPart>(value));
}
template <>
inline const std::string& DateTimestampPart_Name(DateTimestampPart value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DateTimestampPart_descriptor,
                                                 -1, 25>(
      static_cast<int>(value));
}
inline bool DateTimestampPart_Parse(absl::string_view name, DateTimestampPart* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DateTimestampPart>(
      DateTimestampPart_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::googlesql::functions::DateTimestampPart> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::functions::DateTimestampPart>() {
  return ::googlesql::functions::DateTimestampPart_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2ffunctions_2fdatetime_2eproto_2epb_2eh
