// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/datetime.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/functions/datetime.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {
namespace functions {
}  // namespace functions
}  // namespace googlesql
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto = nullptr;
const ::uint32_t TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n)googlesql/public/functions/datetime.pr"
    "oto\022\023googlesql.functions*\257\003\n\021DateTimesta"
    "mpPart\0229\n,__DateTimePart__switch_must_ha"
    "ve_a_default__\020\377\377\377\377\377\377\377\377\377\001\022\010\n\004YEAR\020\001\022\t\n\005M"
    "ONTH\020\002\022\007\n\003DAY\020\003\022\r\n\tDAYOFWEEK\020\004\022\r\n\tDAYOFY"
    "EAR\020\005\022\013\n\007QUARTER\020\006\022\010\n\004HOUR\020\007\022\n\n\006MINUTE\020\010"
    "\022\n\n\006SECOND\020\t\022\017\n\013MILLISECOND\020\n\022\017\n\013MICROSE"
    "COND\020\013\022\016\n\nNANOSECOND\020\014\022\016\n\nPICOSECOND\020\031\022\010"
    "\n\004DATE\020\r\022\010\n\004WEEK\020\016\022\014\n\010DATETIME\020\017\022\010\n\004TIME"
    "\020\020\022\013\n\007ISOYEAR\020\021\022\013\n\007ISOWEEK\020\022\022\017\n\013WEEK_MON"
    "DAY\020\023\022\020\n\014WEEK_TUESDAY\020\024\022\022\n\016WEEK_WEDNESDA"
    "Y\020\025\022\021\n\rWEEK_THURSDAY\020\026\022\017\n\013WEEK_FRIDAY\020\027\022"
    "\021\n\rWEEK_SATURDAY\020\030B3\n\036com.google.googles"
    "ql.functionsB\021GoogleSQLDateTime"
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto = {
    false,
    false,
    551,
    descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto,
    "googlesql/public/functions/datetime.proto",
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto,
};
namespace googlesql {
namespace functions {
const ::google::protobuf::EnumDescriptor* DateTimestampPart_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto);
  return file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DateTimestampPart_internal_data_[] = {
    131071u, 32u, 67108862u, };
bool DateTimestampPart_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, DateTimestampPart_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
