// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/range_sessionize_mode.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto_2epb_2eh
#define googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "googlesql/public/type.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto;
namespace googlesql {
namespace functions {
class RangeSessionizeEnums;
struct RangeSessionizeEnumsDefaultTypeInternal;
extern RangeSessionizeEnumsDefaultTypeInternal _RangeSessionizeEnums_default_instance_;
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {
namespace functions {
enum RangeSessionizeEnums_RangeSessionizeMode : int {
  RangeSessionizeEnums_RangeSessionizeMode_RANGE_SESSIONIZE_MODE_INVALID = 0,
  RangeSessionizeEnums_RangeSessionizeMode_OVERLAPS = 1,
  RangeSessionizeEnums_RangeSessionizeMode_MEETS = 2,
};

bool RangeSessionizeEnums_RangeSessionizeMode_IsValid(int value);
extern const uint32_t RangeSessionizeEnums_RangeSessionizeMode_internal_data_[];
constexpr RangeSessionizeEnums_RangeSessionizeMode RangeSessionizeEnums_RangeSessionizeMode_RangeSessionizeMode_MIN = static_cast<RangeSessionizeEnums_RangeSessionizeMode>(0);
constexpr RangeSessionizeEnums_RangeSessionizeMode RangeSessionizeEnums_RangeSessionizeMode_RangeSessionizeMode_MAX = static_cast<RangeSessionizeEnums_RangeSessionizeMode>(2);
constexpr int RangeSessionizeEnums_RangeSessionizeMode_RangeSessionizeMode_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
RangeSessionizeEnums_RangeSessionizeMode_descriptor();
template <typename T>
const std::string& RangeSessionizeEnums_RangeSessionizeMode_Name(T value) {
  static_assert(std::is_same<T, RangeSessionizeEnums_RangeSessionizeMode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RangeSessionizeMode_Name().");
  return RangeSessionizeEnums_RangeSessionizeMode_Name(static_cast<RangeSessionizeEnums_RangeSessionizeMode>(value));
}
template <>
inline const std::string& RangeSessionizeEnums_RangeSessionizeMode_Name(RangeSessionizeEnums_RangeSessionizeMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RangeSessionizeEnums_RangeSessionizeMode_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool RangeSessionizeEnums_RangeSessionizeMode_Parse(absl::string_view name, RangeSessionizeEnums_RangeSessionizeMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RangeSessionizeEnums_RangeSessionizeMode>(
      RangeSessionizeEnums_RangeSessionizeMode_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class RangeSessionizeEnums final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:googlesql.functions.RangeSessionizeEnums) */ {
 public:
  inline RangeSessionizeEnums() : RangeSessionizeEnums(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RangeSessionizeEnums* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RangeSessionizeEnums));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RangeSessionizeEnums(
      ::google::protobuf::internal::ConstantInitialized);

  inline RangeSessionizeEnums(const RangeSessionizeEnums& from) : RangeSessionizeEnums(nullptr, from) {}
  inline RangeSessionizeEnums(RangeSessionizeEnums&& from) noexcept
      : RangeSessionizeEnums(nullptr, std::move(from)) {}
  inline RangeSessionizeEnums& operator=(const RangeSessionizeEnums& from) {
    CopyFrom(from);
    return *this;
  }
  inline RangeSessionizeEnums& operator=(RangeSessionizeEnums&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RangeSessionizeEnums& default_instance() {
    return *internal_default_instance();
  }
  static inline const RangeSessionizeEnums* internal_default_instance() {
    return reinterpret_cast<const RangeSessionizeEnums*>(
        &_RangeSessionizeEnums_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RangeSessionizeEnums& a, RangeSessionizeEnums& b) { a.Swap(&b); }
  inline void Swap(RangeSessionizeEnums* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RangeSessionizeEnums* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RangeSessionizeEnums* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<RangeSessionizeEnums>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const RangeSessionizeEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const RangeSessionizeEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.functions.RangeSessionizeEnums"; }

 protected:
  explicit RangeSessionizeEnums(::google::protobuf::Arena* arena);
  RangeSessionizeEnums(::google::protobuf::Arena* arena, const RangeSessionizeEnums& from);
  RangeSessionizeEnums(::google::protobuf::Arena* arena, RangeSessionizeEnums&& from) noexcept
      : RangeSessionizeEnums(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using RangeSessionizeMode = RangeSessionizeEnums_RangeSessionizeMode;
  static constexpr RangeSessionizeMode RANGE_SESSIONIZE_MODE_INVALID = RangeSessionizeEnums_RangeSessionizeMode_RANGE_SESSIONIZE_MODE_INVALID;
  static constexpr RangeSessionizeMode OVERLAPS = RangeSessionizeEnums_RangeSessionizeMode_OVERLAPS;
  static constexpr RangeSessionizeMode MEETS = RangeSessionizeEnums_RangeSessionizeMode_MEETS;
  static inline bool RangeSessionizeMode_IsValid(int value) {
    return RangeSessionizeEnums_RangeSessionizeMode_IsValid(value);
  }
  static constexpr RangeSessionizeMode RangeSessionizeMode_MIN = RangeSessionizeEnums_RangeSessionizeMode_RangeSessionizeMode_MIN;
  static constexpr RangeSessionizeMode RangeSessionizeMode_MAX = RangeSessionizeEnums_RangeSessionizeMode_RangeSessionizeMode_MAX;
  static constexpr int RangeSessionizeMode_ARRAYSIZE = RangeSessionizeEnums_RangeSessionizeMode_RangeSessionizeMode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* RangeSessionizeMode_descriptor() {
    return RangeSessionizeEnums_RangeSessionizeMode_descriptor();
  }
  template <typename T>
  static inline const std::string& RangeSessionizeMode_Name(T value) {
    return RangeSessionizeEnums_RangeSessionizeMode_Name(value);
  }
  static inline bool RangeSessionizeMode_Parse(absl::string_view name, RangeSessionizeMode* value) {
    return RangeSessionizeEnums_RangeSessionizeMode_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:googlesql.functions.RangeSessionizeEnums)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RangeSessionizeEnums& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RangeSessionizeEnums

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::googlesql::functions::RangeSessionizeEnums_RangeSessionizeMode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::functions::RangeSessionizeEnums_RangeSessionizeMode>() {
  return ::googlesql::functions::RangeSessionizeEnums_RangeSessionizeMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto_2epb_2eh
