// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/rank_type.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto_2epb_2eh
#define googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "googlesql/public/type.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto;
namespace googlesql {
namespace functions {
class RankTypeEnums;
struct RankTypeEnumsDefaultTypeInternal;
extern RankTypeEnumsDefaultTypeInternal _RankTypeEnums_default_instance_;
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {
namespace functions {
enum RankTypeEnums_RankType : int {
  RankTypeEnums_RankType_RANK_TYPE_UNKNOWN = 0,
  RankTypeEnums_RankType_FRACTION_LESS_THAN_OR_EQUAL = 1,
  RankTypeEnums_RankType_MIDPOINT = 2,
  RankTypeEnums_RankType_FRACTION_LESS_THAN = 3,
};

bool RankTypeEnums_RankType_IsValid(int value);
extern const uint32_t RankTypeEnums_RankType_internal_data_[];
constexpr RankTypeEnums_RankType RankTypeEnums_RankType_RankType_MIN = static_cast<RankTypeEnums_RankType>(0);
constexpr RankTypeEnums_RankType RankTypeEnums_RankType_RankType_MAX = static_cast<RankTypeEnums_RankType>(3);
constexpr int RankTypeEnums_RankType_RankType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
RankTypeEnums_RankType_descriptor();
template <typename T>
const std::string& RankTypeEnums_RankType_Name(T value) {
  static_assert(std::is_same<T, RankTypeEnums_RankType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RankType_Name().");
  return RankTypeEnums_RankType_Name(static_cast<RankTypeEnums_RankType>(value));
}
template <>
inline const std::string& RankTypeEnums_RankType_Name(RankTypeEnums_RankType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RankTypeEnums_RankType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool RankTypeEnums_RankType_Parse(absl::string_view name, RankTypeEnums_RankType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RankTypeEnums_RankType>(
      RankTypeEnums_RankType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class RankTypeEnums final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:googlesql.functions.RankTypeEnums) */ {
 public:
  inline RankTypeEnums() : RankTypeEnums(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RankTypeEnums* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RankTypeEnums));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RankTypeEnums(
      ::google::protobuf::internal::ConstantInitialized);

  inline RankTypeEnums(const RankTypeEnums& from) : RankTypeEnums(nullptr, from) {}
  inline RankTypeEnums(RankTypeEnums&& from) noexcept
      : RankTypeEnums(nullptr, std::move(from)) {}
  inline RankTypeEnums& operator=(const RankTypeEnums& from) {
    CopyFrom(from);
    return *this;
  }
  inline RankTypeEnums& operator=(RankTypeEnums&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RankTypeEnums& default_instance() {
    return *internal_default_instance();
  }
  static inline const RankTypeEnums* internal_default_instance() {
    return reinterpret_cast<const RankTypeEnums*>(
        &_RankTypeEnums_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RankTypeEnums& a, RankTypeEnums& b) { a.Swap(&b); }
  inline void Swap(RankTypeEnums* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RankTypeEnums* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RankTypeEnums* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<RankTypeEnums>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const RankTypeEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const RankTypeEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.functions.RankTypeEnums"; }

 protected:
  explicit RankTypeEnums(::google::protobuf::Arena* arena);
  RankTypeEnums(::google::protobuf::Arena* arena, const RankTypeEnums& from);
  RankTypeEnums(::google::protobuf::Arena* arena, RankTypeEnums&& from) noexcept
      : RankTypeEnums(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using RankType = RankTypeEnums_RankType;
  static constexpr RankType RANK_TYPE_UNKNOWN = RankTypeEnums_RankType_RANK_TYPE_UNKNOWN;
  static constexpr RankType FRACTION_LESS_THAN_OR_EQUAL = RankTypeEnums_RankType_FRACTION_LESS_THAN_OR_EQUAL;
  static constexpr RankType MIDPOINT = RankTypeEnums_RankType_MIDPOINT;
  static constexpr RankType FRACTION_LESS_THAN = RankTypeEnums_RankType_FRACTION_LESS_THAN;
  static inline bool RankType_IsValid(int value) {
    return RankTypeEnums_RankType_IsValid(value);
  }
  static constexpr RankType RankType_MIN = RankTypeEnums_RankType_RankType_MIN;
  static constexpr RankType RankType_MAX = RankTypeEnums_RankType_RankType_MAX;
  static constexpr int RankType_ARRAYSIZE = RankTypeEnums_RankType_RankType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* RankType_descriptor() {
    return RankTypeEnums_RankType_descriptor();
  }
  template <typename T>
  static inline const std::string& RankType_Name(T value) {
    return RankTypeEnums_RankType_Name(value);
  }
  static inline bool RankType_Parse(absl::string_view name, RankType* value) {
    return RankTypeEnums_RankType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:googlesql.functions.RankTypeEnums)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RankTypeEnums& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RankTypeEnums

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::googlesql::functions::RankTypeEnums_RankType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::functions::RankTypeEnums_RankType>() {
  return ::googlesql::functions::RankTypeEnums_RankType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto_2epb_2eh
