// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/rank_type.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/functions/rank_type.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {
namespace functions {
              template <typename>
PROTOBUF_CONSTEXPR RankTypeEnums::RankTypeEnums(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RankTypeEnumsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RankTypeEnumsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RankTypeEnumsDefaultTypeInternal() {}
  union {
    RankTypeEnums _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RankTypeEnumsDefaultTypeInternal _RankTypeEnums_default_instance_;
}  // namespace functions
}  // namespace googlesql
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::RankTypeEnums, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::googlesql::functions::RankTypeEnums)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::functions::_RankTypeEnums_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n*googlesql/public/functions/rank_type.p"
    "roto\022\023googlesql.functions\032\033googlesql/pub"
    "lic/type.proto\"\227\001\n\rRankTypeEnums\"\205\001\n\010Ran"
    "kType\022\037\n\021RANK_TYPE_UNKNOWN\020\000\032\010\262\362\260\222\016\002\010\001\022\037"
    "\n\033FRACTION_LESS_THAN_OR_EQUAL\020\001\022\014\n\010MIDPO"
    "INT\020\002\022\026\n\022FRACTION_LESS_THAN\020\003\032\021\262\320\257\372\r\013\n\tR"
    "ANK_TYPEB3\n\036com.google.googlesql.functio"
    "nsB\021GoogleSQLRankType"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fpublic_2ftype_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto = {
    false,
    false,
    301,
    descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto,
    "googlesql/public/functions/rank_type.proto",
    &descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto_once,
    descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto,
};
namespace googlesql {
namespace functions {
const ::google::protobuf::EnumDescriptor* RankTypeEnums_RankType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto);
  return file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RankTypeEnums_RankType_internal_data_[] = {
    262144u, 0u, };
bool RankTypeEnums_RankType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr RankTypeEnums_RankType RankTypeEnums::RANK_TYPE_UNKNOWN;
constexpr RankTypeEnums_RankType RankTypeEnums::FRACTION_LESS_THAN_OR_EQUAL;
constexpr RankTypeEnums_RankType RankTypeEnums::MIDPOINT;
constexpr RankTypeEnums_RankType RankTypeEnums::FRACTION_LESS_THAN;
constexpr RankTypeEnums_RankType RankTypeEnums::RankType_MIN;
constexpr RankTypeEnums_RankType RankTypeEnums::RankType_MAX;
constexpr int RankTypeEnums::RankType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class RankTypeEnums::_Internal {
 public:
};

RankTypeEnums::RankTypeEnums(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:googlesql.functions.RankTypeEnums)
}
RankTypeEnums::RankTypeEnums(
    ::google::protobuf::Arena* arena,
    const RankTypeEnums& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RankTypeEnums* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:googlesql.functions.RankTypeEnums)
}

inline void* RankTypeEnums::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RankTypeEnums(arena);
}
constexpr auto RankTypeEnums::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RankTypeEnums),
                                            alignof(RankTypeEnums));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RankTypeEnums::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RankTypeEnums_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RankTypeEnums::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<RankTypeEnums>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RankTypeEnums::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<RankTypeEnums>(), &RankTypeEnums::ByteSizeLong,
            &RankTypeEnums::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RankTypeEnums, _impl_._cached_size_),
        false,
    },
    &RankTypeEnums::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RankTypeEnums::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> RankTypeEnums::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::functions::RankTypeEnums>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata RankTypeEnums::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
