// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/rounding_mode.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/functions/rounding_mode.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {
namespace functions {
}  // namespace functions
}  // namespace googlesql
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto = nullptr;
const ::uint32_t TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n.googlesql/public/functions/rounding_mo"
    "de.proto\022\023googlesql.functions\032\033googlesql"
    "/public/type.proto*\202\001\n\014RoundingMode\022\'\n\031R"
    "OUNDING_MODE_UNSPECIFIED\020\000\032\010\262\362\260\222\016\002\010\001\022\035\n\031"
    "ROUND_HALF_AWAY_FROM_ZERO\020\001\022\023\n\017ROUND_HAL"
    "F_EVEN\020\002\032\025\262\320\257\372\r\017\n\rROUNDING_MODEB7\n\036com.g"
    "oogle.googlesql.functionsB\025GoogleSQLRoun"
    "dingMode"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fpublic_2ftype_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto = {
    false,
    false,
    288,
    descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto,
    "googlesql/public/functions/rounding_mode.proto",
    &descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_once,
    descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto,
};
namespace googlesql {
namespace functions {
const ::google::protobuf::EnumDescriptor* RoundingMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto);
  return file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RoundingMode_internal_data_[] = {
    196608u, 0u, };
bool RoundingMode_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
