// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/unsupported_fields.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto_2epb_2eh
#define googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "googlesql/public/type.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto;
namespace googlesql {
namespace functions {
class UnsupportedFieldsEnum;
struct UnsupportedFieldsEnumDefaultTypeInternal;
extern UnsupportedFieldsEnumDefaultTypeInternal _UnsupportedFieldsEnum_default_instance_;
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {
namespace functions {
enum UnsupportedFieldsEnum_UnsupportedFields : int {
  UnsupportedFieldsEnum_UnsupportedFields_UNSUPPORTED_FIELDS_INVALID = 0,
  UnsupportedFieldsEnum_UnsupportedFields_FAIL = 1,
  UnsupportedFieldsEnum_UnsupportedFields_IGNORE = 2,
  UnsupportedFieldsEnum_UnsupportedFields_PLACEHOLDER = 3,
};

bool UnsupportedFieldsEnum_UnsupportedFields_IsValid(int value);
extern const uint32_t UnsupportedFieldsEnum_UnsupportedFields_internal_data_[];
constexpr UnsupportedFieldsEnum_UnsupportedFields UnsupportedFieldsEnum_UnsupportedFields_UnsupportedFields_MIN = static_cast<UnsupportedFieldsEnum_UnsupportedFields>(0);
constexpr UnsupportedFieldsEnum_UnsupportedFields UnsupportedFieldsEnum_UnsupportedFields_UnsupportedFields_MAX = static_cast<UnsupportedFieldsEnum_UnsupportedFields>(3);
constexpr int UnsupportedFieldsEnum_UnsupportedFields_UnsupportedFields_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
UnsupportedFieldsEnum_UnsupportedFields_descriptor();
template <typename T>
const std::string& UnsupportedFieldsEnum_UnsupportedFields_Name(T value) {
  static_assert(std::is_same<T, UnsupportedFieldsEnum_UnsupportedFields>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to UnsupportedFields_Name().");
  return UnsupportedFieldsEnum_UnsupportedFields_Name(static_cast<UnsupportedFieldsEnum_UnsupportedFields>(value));
}
template <>
inline const std::string& UnsupportedFieldsEnum_UnsupportedFields_Name(UnsupportedFieldsEnum_UnsupportedFields value) {
  return ::google::protobuf::internal::NameOfDenseEnum<UnsupportedFieldsEnum_UnsupportedFields_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool UnsupportedFieldsEnum_UnsupportedFields_Parse(absl::string_view name, UnsupportedFieldsEnum_UnsupportedFields* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UnsupportedFieldsEnum_UnsupportedFields>(
      UnsupportedFieldsEnum_UnsupportedFields_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class UnsupportedFieldsEnum final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:googlesql.functions.UnsupportedFieldsEnum) */ {
 public:
  inline UnsupportedFieldsEnum() : UnsupportedFieldsEnum(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UnsupportedFieldsEnum* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UnsupportedFieldsEnum));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UnsupportedFieldsEnum(
      ::google::protobuf::internal::ConstantInitialized);

  inline UnsupportedFieldsEnum(const UnsupportedFieldsEnum& from) : UnsupportedFieldsEnum(nullptr, from) {}
  inline UnsupportedFieldsEnum(UnsupportedFieldsEnum&& from) noexcept
      : UnsupportedFieldsEnum(nullptr, std::move(from)) {}
  inline UnsupportedFieldsEnum& operator=(const UnsupportedFieldsEnum& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnsupportedFieldsEnum& operator=(UnsupportedFieldsEnum&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnsupportedFieldsEnum& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnsupportedFieldsEnum* internal_default_instance() {
    return reinterpret_cast<const UnsupportedFieldsEnum*>(
        &_UnsupportedFieldsEnum_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(UnsupportedFieldsEnum& a, UnsupportedFieldsEnum& b) { a.Swap(&b); }
  inline void Swap(UnsupportedFieldsEnum* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnsupportedFieldsEnum* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnsupportedFieldsEnum* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<UnsupportedFieldsEnum>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const UnsupportedFieldsEnum& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const UnsupportedFieldsEnum& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.functions.UnsupportedFieldsEnum"; }

 protected:
  explicit UnsupportedFieldsEnum(::google::protobuf::Arena* arena);
  UnsupportedFieldsEnum(::google::protobuf::Arena* arena, const UnsupportedFieldsEnum& from);
  UnsupportedFieldsEnum(::google::protobuf::Arena* arena, UnsupportedFieldsEnum&& from) noexcept
      : UnsupportedFieldsEnum(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using UnsupportedFields = UnsupportedFieldsEnum_UnsupportedFields;
  static constexpr UnsupportedFields UNSUPPORTED_FIELDS_INVALID = UnsupportedFieldsEnum_UnsupportedFields_UNSUPPORTED_FIELDS_INVALID;
  static constexpr UnsupportedFields FAIL = UnsupportedFieldsEnum_UnsupportedFields_FAIL;
  static constexpr UnsupportedFields IGNORE = UnsupportedFieldsEnum_UnsupportedFields_IGNORE;
  static constexpr UnsupportedFields PLACEHOLDER = UnsupportedFieldsEnum_UnsupportedFields_PLACEHOLDER;
  static inline bool UnsupportedFields_IsValid(int value) {
    return UnsupportedFieldsEnum_UnsupportedFields_IsValid(value);
  }
  static constexpr UnsupportedFields UnsupportedFields_MIN = UnsupportedFieldsEnum_UnsupportedFields_UnsupportedFields_MIN;
  static constexpr UnsupportedFields UnsupportedFields_MAX = UnsupportedFieldsEnum_UnsupportedFields_UnsupportedFields_MAX;
  static constexpr int UnsupportedFields_ARRAYSIZE = UnsupportedFieldsEnum_UnsupportedFields_UnsupportedFields_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* UnsupportedFields_descriptor() {
    return UnsupportedFieldsEnum_UnsupportedFields_descriptor();
  }
  template <typename T>
  static inline const std::string& UnsupportedFields_Name(T value) {
    return UnsupportedFieldsEnum_UnsupportedFields_Name(value);
  }
  static inline bool UnsupportedFields_Parse(absl::string_view name, UnsupportedFields* value) {
    return UnsupportedFieldsEnum_UnsupportedFields_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:googlesql.functions.UnsupportedFieldsEnum)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UnsupportedFieldsEnum& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UnsupportedFieldsEnum

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace googlesql


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::googlesql::functions::UnsupportedFieldsEnum_UnsupportedFields> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::functions::UnsupportedFieldsEnum_UnsupportedFields>() {
  return ::googlesql::functions::UnsupportedFieldsEnum_UnsupportedFields_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto_2epb_2eh
