// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/proto/type_annotation.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/proto/type_annotation.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {
              template <typename>
PROTOBUF_CONSTEXPR FieldFormat::FieldFormat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct FieldFormatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FieldFormatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FieldFormatDefaultTypeInternal() {}
  union {
    FieldFormat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FieldFormatDefaultTypeInternal _FieldFormat_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR DeprecatedEncoding::DeprecatedEncoding(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct DeprecatedEncodingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeprecatedEncodingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeprecatedEncodingDefaultTypeInternal() {}
  union {
    DeprecatedEncoding _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeprecatedEncodingDefaultTypeInternal _DeprecatedEncoding_default_instance_;
}  // namespace googlesql
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::FieldFormat, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::DeprecatedEncoding, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::googlesql::FieldFormat)},
        {8, -1, -1, sizeof(::googlesql::DeprecatedEncoding)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::_FieldFormat_default_instance_._instance,
    &::googlesql::_DeprecatedEncoding_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n,googlesql/public/proto/type_annotation"
    ".proto\022\tgooglesql\032 google/protobuf/descr"
    "iptor.proto\"\345\003\n\013FieldFormat\"\325\003\n\006Format\022\022"
    "\n\016DEFAULT_FORMAT\020\000\022\010\n\004DATE\020\001\022\025\n\021TIMESTAM"
    "P_SECONDS\020\002\022\024\n\020TIMESTAMP_MILLIS\020\003\022\024\n\020TIM"
    "ESTAMP_MICROS\020\004\022\023\n\017TIMESTAMP_NANOS\020\005\022\023\n\017"
    "TIMESTAMP_PICOS\020\024\022\r\n\tTIMESTAMP\020\025\022\020\n\014DATE"
    "_DECIMAL\020\006\022\017\n\013TIME_MICROS\020\007\022\023\n\017DATETIME_"
    "MICROS\020\010\022\030\n\024ST_GEOGRAPHY_ENCODED\020\t\022\013\n\007NU"
    "MERIC\020\n\022\016\n\nBIGNUMERIC\020\013\022\010\n\004JSON\020\014\022\014\n\010INT"
    "ERVAL\020\016\022\r\n\tTOKENLIST\020\017\022\027\n\023RANGE_DATES_EN"
    "CODED\020\020\022\033\n\027RANGE_DATETIMES_ENCODED\020\021\022\034\n\030"
    "RANGE_TIMESTAMPS_ENCODED\020\022\022\010\n\004UUID\020\023\022=\n0"
    "__FieldFormat_Type__switch_must_have_a_d"
    "efault__\020\377\377\377\377\377\377\377\377\377\001\"\247\001\n\022DeprecatedEncodi"
    "ng\"\220\001\n\010Encoding\022\024\n\020DEFAULT_ENCODING\020\000\022\020\n"
    "\014DATE_DECIMAL\020\001\022\025\n\rDATE_PACKED32\020\001\032\002\010\001\022A"
    "\n4__FieldFormat_Encoding__switch_must_ha"
    "ve_a_default__\020\377\377\377\377\377\377\377\377\377\001\032\002\020\001:O\n\006format\022"
    "\035.google.protobuf.FieldOptions\030\313\353\341  \001(\0162"
    "\035.googlesql.FieldFormat.Format:M\n\004type\022\035"
    ".google.protobuf.FieldOptions\030\345\252\337\027 \001(\0162\035"
    ".googlesql.FieldFormat.Format:Z\n\010encodin"
    "g\022\035.google.protobuf.FieldOptions\030\247\371\376\035 \001("
    "\0162&.googlesql.DeprecatedEncoding.Encodin"
    "g:<\n\014use_defaults\022\035.google.protobuf.Fiel"
    "dOptions\030\277\246\336\027 \001(\010:\004true:D\n\022use_field_def"
    "aults\022\037.google.protobuf.MessageOptions\030\202"
    "\371\326\027 \001(\010:\004trueB.\n\024com.google.googlesqlB\023T"
    "ypeAnnotationProto\370\001\001"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto = {
    false,
    false,
    1181,
    descriptor_table_protodef_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto,
    "googlesql/public/proto/type_annotation.proto",
    &descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto_once,
    descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto,
};
namespace googlesql {
const ::google::protobuf::EnumDescriptor* FieldFormat_Format_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto);
  return file_level_enum_descriptors_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t FieldFormat_Format_internal_data_[] = {
    983039u, 32u, 510u, };
bool FieldFormat_Format_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, FieldFormat_Format_internal_data_);
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr FieldFormat_Format FieldFormat::DEFAULT_FORMAT;
constexpr FieldFormat_Format FieldFormat::DATE;
constexpr FieldFormat_Format FieldFormat::TIMESTAMP_SECONDS;
constexpr FieldFormat_Format FieldFormat::TIMESTAMP_MILLIS;
constexpr FieldFormat_Format FieldFormat::TIMESTAMP_MICROS;
constexpr FieldFormat_Format FieldFormat::TIMESTAMP_NANOS;
constexpr FieldFormat_Format FieldFormat::TIMESTAMP_PICOS;
constexpr FieldFormat_Format FieldFormat::TIMESTAMP;
constexpr FieldFormat_Format FieldFormat::DATE_DECIMAL;
constexpr FieldFormat_Format FieldFormat::TIME_MICROS;
constexpr FieldFormat_Format FieldFormat::DATETIME_MICROS;
constexpr FieldFormat_Format FieldFormat::ST_GEOGRAPHY_ENCODED;
constexpr FieldFormat_Format FieldFormat::NUMERIC;
constexpr FieldFormat_Format FieldFormat::BIGNUMERIC;
constexpr FieldFormat_Format FieldFormat::JSON;
constexpr FieldFormat_Format FieldFormat::INTERVAL;
constexpr FieldFormat_Format FieldFormat::TOKENLIST;
constexpr FieldFormat_Format FieldFormat::RANGE_DATES_ENCODED;
constexpr FieldFormat_Format FieldFormat::RANGE_DATETIMES_ENCODED;
constexpr FieldFormat_Format FieldFormat::RANGE_TIMESTAMPS_ENCODED;
constexpr FieldFormat_Format FieldFormat::UUID;
constexpr FieldFormat_Format FieldFormat::__FieldFormat_Type__switch_must_have_a_default__;
constexpr FieldFormat_Format FieldFormat::Format_MIN;
constexpr FieldFormat_Format FieldFormat::Format_MAX;
constexpr int FieldFormat::Format_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* DeprecatedEncoding_Encoding_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto);
  return file_level_enum_descriptors_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t DeprecatedEncoding_Encoding_internal_data_[] = {
    262143u, 0u, };
bool DeprecatedEncoding_Encoding_IsValid(int value) {
  return -1 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr DeprecatedEncoding_Encoding DeprecatedEncoding::DEFAULT_ENCODING;
constexpr DeprecatedEncoding_Encoding DeprecatedEncoding::DATE_DECIMAL;
constexpr DeprecatedEncoding_Encoding DeprecatedEncoding::DATE_PACKED32;
constexpr DeprecatedEncoding_Encoding DeprecatedEncoding::__FieldFormat_Encoding__switch_must_have_a_default__;
constexpr DeprecatedEncoding_Encoding DeprecatedEncoding::Encoding_MIN;
constexpr DeprecatedEncoding_Encoding DeprecatedEncoding::Encoding_MAX;
constexpr int DeprecatedEncoding::Encoding_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class FieldFormat::_Internal {
 public:
};

FieldFormat::FieldFormat(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:googlesql.FieldFormat)
}
FieldFormat::FieldFormat(
    ::google::protobuf::Arena* arena,
    const FieldFormat& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FieldFormat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:googlesql.FieldFormat)
}

inline void* FieldFormat::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FieldFormat(arena);
}
constexpr auto FieldFormat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FieldFormat),
                                            alignof(FieldFormat));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FieldFormat::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FieldFormat_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FieldFormat::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<FieldFormat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FieldFormat::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<FieldFormat>(), &FieldFormat::ByteSizeLong,
            &FieldFormat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FieldFormat, _impl_._cached_size_),
        false,
    },
    &FieldFormat::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FieldFormat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> FieldFormat::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::FieldFormat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata FieldFormat::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DeprecatedEncoding::_Internal {
 public:
};

DeprecatedEncoding::DeprecatedEncoding(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:googlesql.DeprecatedEncoding)
}
DeprecatedEncoding::DeprecatedEncoding(
    ::google::protobuf::Arena* arena,
    const DeprecatedEncoding& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DeprecatedEncoding* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:googlesql.DeprecatedEncoding)
}

inline void* DeprecatedEncoding::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DeprecatedEncoding(arena);
}
constexpr auto DeprecatedEncoding::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DeprecatedEncoding),
                                            alignof(DeprecatedEncoding));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DeprecatedEncoding::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DeprecatedEncoding_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DeprecatedEncoding::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<DeprecatedEncoding>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DeprecatedEncoding::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<DeprecatedEncoding>(), &DeprecatedEncoding::ByteSizeLong,
            &DeprecatedEncoding::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DeprecatedEncoding, _impl_._cached_size_),
        false,
    },
    &DeprecatedEncoding::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DeprecatedEncoding::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> DeprecatedEncoding::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::DeprecatedEncoding>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata DeprecatedEncoding::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::FieldOptions, ::_pbi::EnumTypeTraits< ::googlesql::FieldFormat_Format, ::googlesql::FieldFormat_Format_IsValid>,
                            14, false>
            format(kFormatFieldNumber, static_cast< ::googlesql::FieldFormat_Format >(0));
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::FieldOptions, ::_pbi::EnumTypeTraits< ::googlesql::FieldFormat_Format, ::googlesql::FieldFormat_Format_IsValid>,
                            14, false>
            type(kTypeFieldNumber, static_cast< ::googlesql::FieldFormat_Format >(0));
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::FieldOptions, ::_pbi::EnumTypeTraits< ::googlesql::DeprecatedEncoding_Encoding, ::googlesql::DeprecatedEncoding_Encoding_IsValid>,
                            14, false>
            encoding(kEncodingFieldNumber, static_cast< ::googlesql::DeprecatedEncoding_Encoding >(0));
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >,
                            8, false>
            use_defaults(kUseDefaultsFieldNumber, true);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::MessageOptions, ::_pbi::PrimitiveTypeTraits< bool >,
                            8, false>
            use_field_defaults(kUseFieldDefaultsFieldNumber, true);
// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::FieldOptions::default_instance(), 68711883, 14,
            false, false, ::googlesql::FieldFormat_Format_IsValid),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::FieldOptions::default_instance(), 49796453, 14,
            false, false, ::googlesql::FieldFormat_Format_IsValid),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::FieldOptions::default_instance(), 62897319, 14,
            false, false, ::googlesql::DeprecatedEncoding_Encoding_IsValid),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 49779519, 8,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::MessageOptions::default_instance(), 49659010, 8,
            false, false),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
