// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/proto/internal_error_location.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fproto_2finternal_5ferror_5flocation_2eproto_2epb_2eh
#define googlesql_2fproto_2finternal_5ferror_5flocation_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "googlesql/public/error_location.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto;
namespace googlesql {
class InternalErrorLocation;
struct InternalErrorLocationDefaultTypeInternal;
extern InternalErrorLocationDefaultTypeInternal _InternalErrorLocation_default_instance_;
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {

// ===================================================================


// -------------------------------------------------------------------

class InternalErrorLocation final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql.InternalErrorLocation) */ {
 public:
  inline InternalErrorLocation() : InternalErrorLocation(nullptr) {}
  ~InternalErrorLocation() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InternalErrorLocation* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InternalErrorLocation));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InternalErrorLocation(
      ::google::protobuf::internal::ConstantInitialized);

  inline InternalErrorLocation(const InternalErrorLocation& from) : InternalErrorLocation(nullptr, from) {}
  inline InternalErrorLocation(InternalErrorLocation&& from) noexcept
      : InternalErrorLocation(nullptr, std::move(from)) {}
  inline InternalErrorLocation& operator=(const InternalErrorLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline InternalErrorLocation& operator=(InternalErrorLocation&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InternalErrorLocation& default_instance() {
    return *internal_default_instance();
  }
  static inline const InternalErrorLocation* internal_default_instance() {
    return reinterpret_cast<const InternalErrorLocation*>(
        &_InternalErrorLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(InternalErrorLocation& a, InternalErrorLocation& b) { a.Swap(&b); }
  inline void Swap(InternalErrorLocation* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InternalErrorLocation* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InternalErrorLocation* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InternalErrorLocation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InternalErrorLocation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InternalErrorLocation& from) { InternalErrorLocation::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InternalErrorLocation* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.InternalErrorLocation"; }

 protected:
  explicit InternalErrorLocation(::google::protobuf::Arena* arena);
  InternalErrorLocation(::google::protobuf::Arena* arena, const InternalErrorLocation& from);
  InternalErrorLocation(::google::protobuf::Arena* arena, InternalErrorLocation&& from) noexcept
      : InternalErrorLocation(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorSourceFieldNumber = 5,
    kFilenameFieldNumber = 4,
    kByteOffsetFieldNumber = 3,
  };
  // repeated .googlesql.ErrorSource error_source = 5;
  int error_source_size() const;
  private:
  int _internal_error_source_size() const;

  public:
  void clear_error_source() ;
  ::googlesql::ErrorSource* mutable_error_source(int index);
  ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>* mutable_error_source();

  private:
  const ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>& _internal_error_source() const;
  ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>* _internal_mutable_error_source();
  public:
  const ::googlesql::ErrorSource& error_source(int index) const;
  ::googlesql::ErrorSource* add_error_source();
  const ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>& error_source() const;
  // optional string filename = 4;
  bool has_filename() const;
  void clear_filename() ;
  const std::string& filename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* value);

  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(
      const std::string& value);
  std::string* _internal_mutable_filename();

  public:
  // optional int32 byte_offset = 3;
  bool has_byte_offset() const;
  void clear_byte_offset() ;
  ::int32_t byte_offset() const;
  void set_byte_offset(::int32_t value);

  private:
  ::int32_t _internal_byte_offset() const;
  void _internal_set_byte_offset(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:googlesql.InternalErrorLocation)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      48, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const InternalErrorLocation& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::googlesql::ErrorSource > error_source_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::int32_t byte_offset_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// InternalErrorLocation

// optional int32 byte_offset = 3;
inline bool InternalErrorLocation::has_byte_offset() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void InternalErrorLocation::clear_byte_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.byte_offset_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t InternalErrorLocation::byte_offset() const {
  // @@protoc_insertion_point(field_get:googlesql.InternalErrorLocation.byte_offset)
  return _internal_byte_offset();
}
inline void InternalErrorLocation::set_byte_offset(::int32_t value) {
  _internal_set_byte_offset(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:googlesql.InternalErrorLocation.byte_offset)
}
inline ::int32_t InternalErrorLocation::_internal_byte_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.byte_offset_;
}
inline void InternalErrorLocation::_internal_set_byte_offset(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.byte_offset_ = value;
}

// optional string filename = 4;
inline bool InternalErrorLocation::has_filename() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void InternalErrorLocation::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& InternalErrorLocation::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.InternalErrorLocation.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InternalErrorLocation::set_filename(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:googlesql.InternalErrorLocation.filename)
}
inline std::string* InternalErrorLocation::mutable_filename() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:googlesql.InternalErrorLocation.filename)
  return _s;
}
inline const std::string& InternalErrorLocation::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void InternalErrorLocation::_internal_set_filename(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(value, GetArena());
}
inline std::string* InternalErrorLocation::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.filename_.Mutable( GetArena());
}
inline std::string* InternalErrorLocation::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.InternalErrorLocation.filename)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.filename_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.filename_.Set("", GetArena());
  }
  return released;
}
inline void InternalErrorLocation::set_allocated_filename(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:googlesql.InternalErrorLocation.filename)
}

// repeated .googlesql.ErrorSource error_source = 5;
inline int InternalErrorLocation::_internal_error_source_size() const {
  return _internal_error_source().size();
}
inline int InternalErrorLocation::error_source_size() const {
  return _internal_error_source_size();
}
inline ::googlesql::ErrorSource* InternalErrorLocation::mutable_error_source(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:googlesql.InternalErrorLocation.error_source)
  return _internal_mutable_error_source()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>* InternalErrorLocation::mutable_error_source()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:googlesql.InternalErrorLocation.error_source)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_error_source();
}
inline const ::googlesql::ErrorSource& InternalErrorLocation::error_source(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.InternalErrorLocation.error_source)
  return _internal_error_source().Get(index);
}
inline ::googlesql::ErrorSource* InternalErrorLocation::add_error_source() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::googlesql::ErrorSource* _add = _internal_mutable_error_source()->Add();
  // @@protoc_insertion_point(field_add:googlesql.InternalErrorLocation.error_source)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>& InternalErrorLocation::error_source() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:googlesql.InternalErrorLocation.error_source)
  return _internal_error_source();
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>&
InternalErrorLocation::_internal_error_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_source_;
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::ErrorSource>*
InternalErrorLocation::_internal_mutable_error_source() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.error_source_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fproto_2finternal_5ferror_5flocation_2eproto_2epb_2eh
