// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/proto/internal_fix_suggestion.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/proto/internal_fix_suggestion.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {

inline constexpr InternalFixRange::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        start_{nullptr},
        length_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InternalFixRange::InternalFixRange(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InternalFixRangeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InternalFixRangeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InternalFixRangeDefaultTypeInternal() {}
  union {
    InternalFixRange _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InternalFixRangeDefaultTypeInternal _InternalFixRange_default_instance_;

inline constexpr InternalTextEdit::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        new_text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        range_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR InternalTextEdit::InternalTextEdit(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InternalTextEditDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InternalTextEditDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InternalTextEditDefaultTypeInternal() {}
  union {
    InternalTextEdit _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InternalTextEditDefaultTypeInternal _InternalTextEdit_default_instance_;

inline constexpr InternalEdits::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : text_edits_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InternalEdits::InternalEdits(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InternalEditsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InternalEditsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InternalEditsDefaultTypeInternal() {}
  union {
    InternalEdits _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InternalEditsDefaultTypeInternal _InternalEdits_default_instance_;

inline constexpr InternalFix::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        edits_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR InternalFix::InternalFix(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InternalFixDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InternalFixDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InternalFixDefaultTypeInternal() {}
  union {
    InternalFix _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InternalFixDefaultTypeInternal _InternalFix_default_instance_;

inline constexpr InternalErrorFixSuggestions::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : fix_suggestions_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InternalErrorFixSuggestions::InternalErrorFixSuggestions(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InternalErrorFixSuggestionsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InternalErrorFixSuggestionsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InternalErrorFixSuggestionsDefaultTypeInternal() {}
  union {
    InternalErrorFixSuggestions _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InternalErrorFixSuggestionsDefaultTypeInternal _InternalErrorFixSuggestions_default_instance_;
}  // namespace googlesql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFixRange, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFixRange, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFixRange, _impl_.start_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFixRange, _impl_.length_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalTextEdit, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalTextEdit, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalTextEdit, _impl_.range_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalTextEdit, _impl_.new_text_),
        1,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalEdits, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalEdits, _impl_.text_edits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFix, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFix, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFix, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalFix, _impl_.edits_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalErrorFixSuggestions, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalErrorFixSuggestions, _impl_.fix_suggestions_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::googlesql::InternalFixRange)},
        {12, 22, -1, sizeof(::googlesql::InternalTextEdit)},
        {24, -1, -1, sizeof(::googlesql::InternalEdits)},
        {33, 43, -1, sizeof(::googlesql::InternalFix)},
        {45, -1, -1, sizeof(::googlesql::InternalErrorFixSuggestions)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::_InternalFixRange_default_instance_._instance,
    &::googlesql::_InternalTextEdit_default_instance_._instance,
    &::googlesql::_InternalEdits_default_instance_._instance,
    &::googlesql::_InternalFix_default_instance_._instance,
    &::googlesql::_InternalErrorFixSuggestions_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n-googlesql/proto/internal_fix_suggestio"
    "n.proto\022\tgooglesql\032-googlesql/proto/inte"
    "rnal_error_location.proto\"S\n\020InternalFix"
    "Range\022/\n\005start\030\001 \001(\0132 .googlesql.Interna"
    "lErrorLocation\022\016\n\006length\030\002 \001(\005\"P\n\020Intern"
    "alTextEdit\022*\n\005range\030\001 \001(\0132\033.googlesql.In"
    "ternalFixRange\022\020\n\010new_text\030\002 \001(\t\"@\n\rInte"
    "rnalEdits\022/\n\ntext_edits\030\001 \003(\0132\033.googlesq"
    "l.InternalTextEdit\"E\n\013InternalFix\022\r\n\005tit"
    "le\030\001 \001(\t\022\'\n\005edits\030\002 \001(\0132\030.googlesql.Inte"
    "rnalEdits\"N\n\033InternalErrorFixSuggestions"
    "\022/\n\017fix_suggestions\030\001 \003(\0132\026.googlesql.In"
    "ternalFixB3\n\024com.google.googlesqlB\033Inter"
    "nalFixSuggestionProtos"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto = {
    false,
    false,
    542,
    descriptor_table_protodef_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
    "googlesql/proto/internal_fix_suggestion.proto",
    &descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto_once,
    descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
    file_level_service_descriptors_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
};
namespace googlesql {
// ===================================================================

class InternalFixRange::_Internal {
 public:
  using HasBits =
      decltype(std::declval<InternalFixRange>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_._has_bits_);
};

void InternalFixRange::clear_start() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.start_ != nullptr) _impl_.start_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
InternalFixRange::InternalFixRange(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.InternalFixRange)
}
inline PROTOBUF_NDEBUG_INLINE InternalFixRange::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::InternalFixRange& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

InternalFixRange::InternalFixRange(
    ::google::protobuf::Arena* arena,
    const InternalFixRange& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InternalFixRange* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.start_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::InternalErrorLocation>(
                              arena, *from._impl_.start_)
                        : nullptr;
  _impl_.length_ = from._impl_.length_;

  // @@protoc_insertion_point(copy_constructor:googlesql.InternalFixRange)
}
inline PROTOBUF_NDEBUG_INLINE InternalFixRange::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void InternalFixRange::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_),
           0,
           offsetof(Impl_, length_) -
               offsetof(Impl_, start_) +
               sizeof(Impl_::length_));
}
InternalFixRange::~InternalFixRange() {
  // @@protoc_insertion_point(destructor:googlesql.InternalFixRange)
  SharedDtor(*this);
}
inline void InternalFixRange::SharedDtor(MessageLite& self) {
  InternalFixRange& this_ = static_cast<InternalFixRange&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.start_;
  this_._impl_.~Impl_();
}

inline void* InternalFixRange::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InternalFixRange(arena);
}
constexpr auto InternalFixRange::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(InternalFixRange),
                                            alignof(InternalFixRange));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InternalFixRange::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InternalFixRange_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InternalFixRange::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InternalFixRange>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InternalFixRange::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InternalFixRange>(), &InternalFixRange::ByteSizeLong,
            &InternalFixRange::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_._cached_size_),
        false,
    },
    &InternalFixRange::kDescriptorMethods,
    &descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InternalFixRange::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> InternalFixRange::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::InternalFixRange>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 length = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InternalFixRange, _impl_.length_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_.length_)}},
    // optional .googlesql.InternalErrorLocation start = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_.start_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .googlesql.InternalErrorLocation start = 1;
    {PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_.start_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int32 length = 2;
    {PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_.length_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::InternalErrorLocation>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void InternalFixRange::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.InternalFixRange)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.start_ != nullptr);
    _impl_.start_->Clear();
  }
  _impl_.length_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InternalFixRange::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InternalFixRange& this_ = static_cast<const InternalFixRange&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InternalFixRange::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InternalFixRange& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.InternalFixRange)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .googlesql.InternalErrorLocation start = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.start_, this_._impl_.start_->GetCachedSize(), target,
                stream);
          }

          // optional int32 length = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_length(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.InternalFixRange)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InternalFixRange::ByteSizeLong(const MessageLite& base) {
          const InternalFixRange& this_ = static_cast<const InternalFixRange&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InternalFixRange::ByteSizeLong() const {
          const InternalFixRange& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.InternalFixRange)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional .googlesql.InternalErrorLocation start = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.start_);
            }
            // optional int32 length = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_length());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InternalFixRange::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InternalFixRange*>(&to_msg);
  auto& from = static_cast<const InternalFixRange&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.InternalFixRange)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.start_ != nullptr);
      if (_this->_impl_.start_ == nullptr) {
        _this->_impl_.start_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::InternalErrorLocation>(arena, *from._impl_.start_);
      } else {
        _this->_impl_.start_->MergeFrom(*from._impl_.start_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.length_ = from._impl_.length_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InternalFixRange::CopyFrom(const InternalFixRange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.InternalFixRange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InternalFixRange::InternalSwap(InternalFixRange* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_.length_)
      + sizeof(InternalFixRange::_impl_.length_)
      - PROTOBUF_FIELD_OFFSET(InternalFixRange, _impl_.start_)>(
          reinterpret_cast<char*>(&_impl_.start_),
          reinterpret_cast<char*>(&other->_impl_.start_));
}

::google::protobuf::Metadata InternalFixRange::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InternalTextEdit::_Internal {
 public:
  using HasBits =
      decltype(std::declval<InternalTextEdit>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InternalTextEdit, _impl_._has_bits_);
};

InternalTextEdit::InternalTextEdit(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.InternalTextEdit)
}
inline PROTOBUF_NDEBUG_INLINE InternalTextEdit::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::InternalTextEdit& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        new_text_(arena, from.new_text_) {}

InternalTextEdit::InternalTextEdit(
    ::google::protobuf::Arena* arena,
    const InternalTextEdit& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InternalTextEdit* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.range_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::InternalFixRange>(
                              arena, *from._impl_.range_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:googlesql.InternalTextEdit)
}
inline PROTOBUF_NDEBUG_INLINE InternalTextEdit::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        new_text_(arena) {}

inline void InternalTextEdit::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.range_ = {};
}
InternalTextEdit::~InternalTextEdit() {
  // @@protoc_insertion_point(destructor:googlesql.InternalTextEdit)
  SharedDtor(*this);
}
inline void InternalTextEdit::SharedDtor(MessageLite& self) {
  InternalTextEdit& this_ = static_cast<InternalTextEdit&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.new_text_.Destroy();
  delete this_._impl_.range_;
  this_._impl_.~Impl_();
}

inline void* InternalTextEdit::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InternalTextEdit(arena);
}
constexpr auto InternalTextEdit::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(InternalTextEdit),
                                            alignof(InternalTextEdit));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InternalTextEdit::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InternalTextEdit_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InternalTextEdit::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InternalTextEdit>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InternalTextEdit::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InternalTextEdit>(), &InternalTextEdit::ByteSizeLong,
            &InternalTextEdit::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InternalTextEdit, _impl_._cached_size_),
        false,
    },
    &InternalTextEdit::kDescriptorMethods,
    &descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InternalTextEdit::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 43, 2> InternalTextEdit::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InternalTextEdit, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::InternalTextEdit>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string new_text = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(InternalTextEdit, _impl_.new_text_)}},
    // optional .googlesql.InternalFixRange range = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0, PROTOBUF_FIELD_OFFSET(InternalTextEdit, _impl_.range_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .googlesql.InternalFixRange range = 1;
    {PROTOBUF_FIELD_OFFSET(InternalTextEdit, _impl_.range_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string new_text = 2;
    {PROTOBUF_FIELD_OFFSET(InternalTextEdit, _impl_.new_text_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::InternalFixRange>()},
  }}, {{
    "\32\0\10\0\0\0\0\0"
    "googlesql.InternalTextEdit"
    "new_text"
  }},
};

PROTOBUF_NOINLINE void InternalTextEdit::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.InternalTextEdit)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.new_text_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.range_ != nullptr);
      _impl_.range_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InternalTextEdit::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InternalTextEdit& this_ = static_cast<const InternalTextEdit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InternalTextEdit::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InternalTextEdit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.InternalTextEdit)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .googlesql.InternalFixRange range = 1;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.range_, this_._impl_.range_->GetCachedSize(), target,
                stream);
          }

          // optional string new_text = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_new_text();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.InternalTextEdit.new_text");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.InternalTextEdit)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InternalTextEdit::ByteSizeLong(const MessageLite& base) {
          const InternalTextEdit& this_ = static_cast<const InternalTextEdit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InternalTextEdit::ByteSizeLong() const {
          const InternalTextEdit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.InternalTextEdit)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string new_text = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_new_text());
            }
            // optional .googlesql.InternalFixRange range = 1;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.range_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InternalTextEdit::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InternalTextEdit*>(&to_msg);
  auto& from = static_cast<const InternalTextEdit&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.InternalTextEdit)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_new_text(from._internal_new_text());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.range_ != nullptr);
      if (_this->_impl_.range_ == nullptr) {
        _this->_impl_.range_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::InternalFixRange>(arena, *from._impl_.range_);
      } else {
        _this->_impl_.range_->MergeFrom(*from._impl_.range_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InternalTextEdit::CopyFrom(const InternalTextEdit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.InternalTextEdit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InternalTextEdit::InternalSwap(InternalTextEdit* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.new_text_, &other->_impl_.new_text_, arena);
  swap(_impl_.range_, other->_impl_.range_);
}

::google::protobuf::Metadata InternalTextEdit::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InternalEdits::_Internal {
 public:
};

InternalEdits::InternalEdits(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.InternalEdits)
}
inline PROTOBUF_NDEBUG_INLINE InternalEdits::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::InternalEdits& from_msg)
      : text_edits_{visibility, arena, from.text_edits_},
        _cached_size_{0} {}

InternalEdits::InternalEdits(
    ::google::protobuf::Arena* arena,
    const InternalEdits& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InternalEdits* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:googlesql.InternalEdits)
}
inline PROTOBUF_NDEBUG_INLINE InternalEdits::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : text_edits_{visibility, arena},
        _cached_size_{0} {}

inline void InternalEdits::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
InternalEdits::~InternalEdits() {
  // @@protoc_insertion_point(destructor:googlesql.InternalEdits)
  SharedDtor(*this);
}
inline void InternalEdits::SharedDtor(MessageLite& self) {
  InternalEdits& this_ = static_cast<InternalEdits&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* InternalEdits::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InternalEdits(arena);
}
constexpr auto InternalEdits::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(InternalEdits, _impl_.text_edits_) +
          decltype(InternalEdits::_impl_.text_edits_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(InternalEdits), alignof(InternalEdits), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&InternalEdits::PlacementNew_,
                                 sizeof(InternalEdits),
                                 alignof(InternalEdits));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InternalEdits::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InternalEdits_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InternalEdits::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InternalEdits>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InternalEdits::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InternalEdits>(), &InternalEdits::ByteSizeLong,
            &InternalEdits::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InternalEdits, _impl_._cached_size_),
        false,
    },
    &InternalEdits::kDescriptorMethods,
    &descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InternalEdits::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> InternalEdits::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::InternalEdits>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .googlesql.InternalTextEdit text_edits = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(InternalEdits, _impl_.text_edits_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .googlesql.InternalTextEdit text_edits = 1;
    {PROTOBUF_FIELD_OFFSET(InternalEdits, _impl_.text_edits_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::InternalTextEdit>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void InternalEdits::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.InternalEdits)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_edits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InternalEdits::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InternalEdits& this_ = static_cast<const InternalEdits&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InternalEdits::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InternalEdits& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.InternalEdits)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .googlesql.InternalTextEdit text_edits = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_text_edits_size());
               i < n; i++) {
            const auto& repfield = this_._internal_text_edits().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.InternalEdits)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InternalEdits::ByteSizeLong(const MessageLite& base) {
          const InternalEdits& this_ = static_cast<const InternalEdits&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InternalEdits::ByteSizeLong() const {
          const InternalEdits& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.InternalEdits)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.InternalTextEdit text_edits = 1;
            {
              total_size += 1UL * this_._internal_text_edits_size();
              for (const auto& msg : this_._internal_text_edits()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InternalEdits::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InternalEdits*>(&to_msg);
  auto& from = static_cast<const InternalEdits&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.InternalEdits)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_text_edits()->MergeFrom(
      from._internal_text_edits());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InternalEdits::CopyFrom(const InternalEdits& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.InternalEdits)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InternalEdits::InternalSwap(InternalEdits* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.text_edits_.InternalSwap(&other->_impl_.text_edits_);
}

::google::protobuf::Metadata InternalEdits::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InternalFix::_Internal {
 public:
  using HasBits =
      decltype(std::declval<InternalFix>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InternalFix, _impl_._has_bits_);
};

InternalFix::InternalFix(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.InternalFix)
}
inline PROTOBUF_NDEBUG_INLINE InternalFix::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::InternalFix& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        title_(arena, from.title_) {}

InternalFix::InternalFix(
    ::google::protobuf::Arena* arena,
    const InternalFix& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InternalFix* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.edits_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::InternalEdits>(
                              arena, *from._impl_.edits_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:googlesql.InternalFix)
}
inline PROTOBUF_NDEBUG_INLINE InternalFix::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        title_(arena) {}

inline void InternalFix::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.edits_ = {};
}
InternalFix::~InternalFix() {
  // @@protoc_insertion_point(destructor:googlesql.InternalFix)
  SharedDtor(*this);
}
inline void InternalFix::SharedDtor(MessageLite& self) {
  InternalFix& this_ = static_cast<InternalFix&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.title_.Destroy();
  delete this_._impl_.edits_;
  this_._impl_.~Impl_();
}

inline void* InternalFix::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InternalFix(arena);
}
constexpr auto InternalFix::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(InternalFix),
                                            alignof(InternalFix));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InternalFix::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InternalFix_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InternalFix::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InternalFix>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InternalFix::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InternalFix>(), &InternalFix::ByteSizeLong,
            &InternalFix::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InternalFix, _impl_._cached_size_),
        false,
    },
    &InternalFix::kDescriptorMethods,
    &descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InternalFix::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 35, 2> InternalFix::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InternalFix, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::InternalFix>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .googlesql.InternalEdits edits = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(InternalFix, _impl_.edits_)}},
    // optional string title = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(InternalFix, _impl_.title_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string title = 1;
    {PROTOBUF_FIELD_OFFSET(InternalFix, _impl_.title_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional .googlesql.InternalEdits edits = 2;
    {PROTOBUF_FIELD_OFFSET(InternalFix, _impl_.edits_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::InternalEdits>()},
  }}, {{
    "\25\5\0\0\0\0\0\0"
    "googlesql.InternalFix"
    "title"
  }},
};

PROTOBUF_NOINLINE void InternalFix::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.InternalFix)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.edits_ != nullptr);
      _impl_.edits_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InternalFix::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InternalFix& this_ = static_cast<const InternalFix&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InternalFix::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InternalFix& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.InternalFix)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string title = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_title();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.InternalFix.title");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional .googlesql.InternalEdits edits = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.edits_, this_._impl_.edits_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.InternalFix)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InternalFix::ByteSizeLong(const MessageLite& base) {
          const InternalFix& this_ = static_cast<const InternalFix&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InternalFix::ByteSizeLong() const {
          const InternalFix& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.InternalFix)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string title = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_title());
            }
            // optional .googlesql.InternalEdits edits = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.edits_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InternalFix::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InternalFix*>(&to_msg);
  auto& from = static_cast<const InternalFix&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.InternalFix)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_title(from._internal_title());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.edits_ != nullptr);
      if (_this->_impl_.edits_ == nullptr) {
        _this->_impl_.edits_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::InternalEdits>(arena, *from._impl_.edits_);
      } else {
        _this->_impl_.edits_->MergeFrom(*from._impl_.edits_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InternalFix::CopyFrom(const InternalFix& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.InternalFix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InternalFix::InternalSwap(InternalFix* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  swap(_impl_.edits_, other->_impl_.edits_);
}

::google::protobuf::Metadata InternalFix::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InternalErrorFixSuggestions::_Internal {
 public:
};

InternalErrorFixSuggestions::InternalErrorFixSuggestions(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.InternalErrorFixSuggestions)
}
inline PROTOBUF_NDEBUG_INLINE InternalErrorFixSuggestions::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::InternalErrorFixSuggestions& from_msg)
      : fix_suggestions_{visibility, arena, from.fix_suggestions_},
        _cached_size_{0} {}

InternalErrorFixSuggestions::InternalErrorFixSuggestions(
    ::google::protobuf::Arena* arena,
    const InternalErrorFixSuggestions& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InternalErrorFixSuggestions* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:googlesql.InternalErrorFixSuggestions)
}
inline PROTOBUF_NDEBUG_INLINE InternalErrorFixSuggestions::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : fix_suggestions_{visibility, arena},
        _cached_size_{0} {}

inline void InternalErrorFixSuggestions::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
InternalErrorFixSuggestions::~InternalErrorFixSuggestions() {
  // @@protoc_insertion_point(destructor:googlesql.InternalErrorFixSuggestions)
  SharedDtor(*this);
}
inline void InternalErrorFixSuggestions::SharedDtor(MessageLite& self) {
  InternalErrorFixSuggestions& this_ = static_cast<InternalErrorFixSuggestions&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* InternalErrorFixSuggestions::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InternalErrorFixSuggestions(arena);
}
constexpr auto InternalErrorFixSuggestions::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(InternalErrorFixSuggestions, _impl_.fix_suggestions_) +
          decltype(InternalErrorFixSuggestions::_impl_.fix_suggestions_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(InternalErrorFixSuggestions), alignof(InternalErrorFixSuggestions), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&InternalErrorFixSuggestions::PlacementNew_,
                                 sizeof(InternalErrorFixSuggestions),
                                 alignof(InternalErrorFixSuggestions));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InternalErrorFixSuggestions::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InternalErrorFixSuggestions_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InternalErrorFixSuggestions::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InternalErrorFixSuggestions>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InternalErrorFixSuggestions::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InternalErrorFixSuggestions>(), &InternalErrorFixSuggestions::ByteSizeLong,
            &InternalErrorFixSuggestions::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InternalErrorFixSuggestions, _impl_._cached_size_),
        false,
    },
    &InternalErrorFixSuggestions::kDescriptorMethods,
    &descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InternalErrorFixSuggestions::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> InternalErrorFixSuggestions::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::InternalErrorFixSuggestions>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .googlesql.InternalFix fix_suggestions = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(InternalErrorFixSuggestions, _impl_.fix_suggestions_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .googlesql.InternalFix fix_suggestions = 1;
    {PROTOBUF_FIELD_OFFSET(InternalErrorFixSuggestions, _impl_.fix_suggestions_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::InternalFix>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void InternalErrorFixSuggestions::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.InternalErrorFixSuggestions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fix_suggestions_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InternalErrorFixSuggestions::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InternalErrorFixSuggestions& this_ = static_cast<const InternalErrorFixSuggestions&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InternalErrorFixSuggestions::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InternalErrorFixSuggestions& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.InternalErrorFixSuggestions)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .googlesql.InternalFix fix_suggestions = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_fix_suggestions_size());
               i < n; i++) {
            const auto& repfield = this_._internal_fix_suggestions().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.InternalErrorFixSuggestions)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InternalErrorFixSuggestions::ByteSizeLong(const MessageLite& base) {
          const InternalErrorFixSuggestions& this_ = static_cast<const InternalErrorFixSuggestions&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InternalErrorFixSuggestions::ByteSizeLong() const {
          const InternalErrorFixSuggestions& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.InternalErrorFixSuggestions)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.InternalFix fix_suggestions = 1;
            {
              total_size += 1UL * this_._internal_fix_suggestions_size();
              for (const auto& msg : this_._internal_fix_suggestions()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InternalErrorFixSuggestions::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InternalErrorFixSuggestions*>(&to_msg);
  auto& from = static_cast<const InternalErrorFixSuggestions&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.InternalErrorFixSuggestions)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_fix_suggestions()->MergeFrom(
      from._internal_fix_suggestions());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InternalErrorFixSuggestions::CopyFrom(const InternalErrorFixSuggestions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.InternalErrorFixSuggestions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InternalErrorFixSuggestions::InternalSwap(InternalErrorFixSuggestions* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.fix_suggestions_.InternalSwap(&other->_impl_.fix_suggestions_);
}

::google::protobuf::Metadata InternalErrorFixSuggestions::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
