// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/proto/internal_error_location.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/proto/internal_error_location.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {

inline constexpr InternalErrorLocation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        error_source_{},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        byte_offset_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InternalErrorLocation::InternalErrorLocation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InternalErrorLocationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InternalErrorLocationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InternalErrorLocationDefaultTypeInternal() {}
  union {
    InternalErrorLocation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InternalErrorLocationDefaultTypeInternal _InternalErrorLocation_default_instance_;
}  // namespace googlesql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalErrorLocation, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalErrorLocation, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalErrorLocation, _impl_.byte_offset_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalErrorLocation, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::googlesql::InternalErrorLocation, _impl_.error_source_),
        1,
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::googlesql::InternalErrorLocation)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::_InternalErrorLocation_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n-googlesql/proto/internal_error_locatio"
    "n.proto\022\tgooglesql\032%googlesql/public/err"
    "or_location.proto\"l\n\025InternalErrorLocati"
    "on\022\023\n\013byte_offset\030\003 \001(\005\022\020\n\010filename\030\004 \001("
    "\t\022,\n\014error_source\030\005 \003(\0132\026.googlesql.Erro"
    "rSourceB3\n\024com.google.googlesqlB\033Interna"
    "lErrorLocationProtos"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto = {
    false,
    false,
    260,
    descriptor_table_protodef_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto,
    "googlesql/proto/internal_error_location.proto",
    &descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto_once,
    descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto,
    file_level_service_descriptors_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto,
};
namespace googlesql {
// ===================================================================

class InternalErrorLocation::_Internal {
 public:
  using HasBits =
      decltype(std::declval<InternalErrorLocation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_._has_bits_);
};

void InternalErrorLocation::clear_error_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_source_.Clear();
}
InternalErrorLocation::InternalErrorLocation(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.InternalErrorLocation)
}
inline PROTOBUF_NDEBUG_INLINE InternalErrorLocation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::InternalErrorLocation& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        error_source_{visibility, arena, from.error_source_},
        filename_(arena, from.filename_) {}

InternalErrorLocation::InternalErrorLocation(
    ::google::protobuf::Arena* arena,
    const InternalErrorLocation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InternalErrorLocation* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.byte_offset_ = from._impl_.byte_offset_;

  // @@protoc_insertion_point(copy_constructor:googlesql.InternalErrorLocation)
}
inline PROTOBUF_NDEBUG_INLINE InternalErrorLocation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        error_source_{visibility, arena},
        filename_(arena) {}

inline void InternalErrorLocation::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.byte_offset_ = {};
}
InternalErrorLocation::~InternalErrorLocation() {
  // @@protoc_insertion_point(destructor:googlesql.InternalErrorLocation)
  SharedDtor(*this);
}
inline void InternalErrorLocation::SharedDtor(MessageLite& self) {
  InternalErrorLocation& this_ = static_cast<InternalErrorLocation&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* InternalErrorLocation::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InternalErrorLocation(arena);
}
constexpr auto InternalErrorLocation::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_.error_source_) +
          decltype(InternalErrorLocation::_impl_.error_source_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(InternalErrorLocation), alignof(InternalErrorLocation), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&InternalErrorLocation::PlacementNew_,
                                 sizeof(InternalErrorLocation),
                                 alignof(InternalErrorLocation));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InternalErrorLocation::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InternalErrorLocation_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InternalErrorLocation::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InternalErrorLocation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InternalErrorLocation::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InternalErrorLocation>(), &InternalErrorLocation::ByteSizeLong,
            &InternalErrorLocation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_._cached_size_),
        false,
    },
    &InternalErrorLocation::kDescriptorMethods,
    &descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InternalErrorLocation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 48, 2> InternalErrorLocation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_._has_bits_),
    0, // no _extensions_
    5, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967267,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::InternalErrorLocation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string filename = 4;
    {::_pbi::TcParser::FastSS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_.filename_)}},
    // repeated .googlesql.ErrorSource error_source = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_.error_source_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 byte_offset = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InternalErrorLocation, _impl_.byte_offset_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_.byte_offset_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 byte_offset = 3;
    {PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_.byte_offset_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string filename = 4;
    {PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated .googlesql.ErrorSource error_source = 5;
    {PROTOBUF_FIELD_OFFSET(InternalErrorLocation, _impl_.error_source_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::ErrorSource>()},
  }}, {{
    "\37\0\10\0\0\0\0\0"
    "googlesql.InternalErrorLocation"
    "filename"
  }},
};

PROTOBUF_NOINLINE void InternalErrorLocation::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.InternalErrorLocation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_source_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.filename_.ClearNonDefaultToEmpty();
  }
  _impl_.byte_offset_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InternalErrorLocation::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InternalErrorLocation& this_ = static_cast<const InternalErrorLocation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InternalErrorLocation::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InternalErrorLocation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.InternalErrorLocation)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 byte_offset = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_byte_offset(), target);
          }

          // optional string filename = 4;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_filename();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.InternalErrorLocation.filename");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // repeated .googlesql.ErrorSource error_source = 5;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_error_source_size());
               i < n; i++) {
            const auto& repfield = this_._internal_error_source().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    5, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.InternalErrorLocation)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InternalErrorLocation::ByteSizeLong(const MessageLite& base) {
          const InternalErrorLocation& this_ = static_cast<const InternalErrorLocation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InternalErrorLocation::ByteSizeLong() const {
          const InternalErrorLocation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.InternalErrorLocation)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.ErrorSource error_source = 5;
            {
              total_size += 1UL * this_._internal_error_source_size();
              for (const auto& msg : this_._internal_error_source()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string filename = 4;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filename());
            }
            // optional int32 byte_offset = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_byte_offset());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InternalErrorLocation::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InternalErrorLocation*>(&to_msg);
  auto& from = static_cast<const InternalErrorLocation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.InternalErrorLocation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_error_source()->MergeFrom(
      from._internal_error_source());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_filename(from._internal_filename());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.byte_offset_ = from._impl_.byte_offset_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InternalErrorLocation::CopyFrom(const InternalErrorLocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.InternalErrorLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InternalErrorLocation::InternalSwap(InternalErrorLocation* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.error_source_.InternalSwap(&other->_impl_.error_source_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
        swap(_impl_.byte_offset_, other->_impl_.byte_offset_);
}

::google::protobuf::Metadata InternalErrorLocation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
