// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/proto/script_exception.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fproto_2fscript_5fexception_2eproto_2epb_2eh
#define googlesql_2fproto_2fscript_5fexception_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fproto_2fscript_5fexception_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fproto_2fscript_5fexception_2eproto;
namespace googlesql {
class ScriptException;
struct ScriptExceptionDefaultTypeInternal;
extern ScriptExceptionDefaultTypeInternal _ScriptException_default_instance_;
class ScriptException_Internal;
struct ScriptException_InternalDefaultTypeInternal;
extern ScriptException_InternalDefaultTypeInternal _ScriptException_Internal_default_instance_;
class ScriptException_StackTraceFrame;
struct ScriptException_StackTraceFrameDefaultTypeInternal;
extern ScriptException_StackTraceFrameDefaultTypeInternal _ScriptException_StackTraceFrame_default_instance_;
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {

// ===================================================================


// -------------------------------------------------------------------

class ScriptException_StackTraceFrame final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql.ScriptException.StackTraceFrame) */ {
 public:
  inline ScriptException_StackTraceFrame() : ScriptException_StackTraceFrame(nullptr) {}
  ~ScriptException_StackTraceFrame() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ScriptException_StackTraceFrame* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ScriptException_StackTraceFrame));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ScriptException_StackTraceFrame(
      ::google::protobuf::internal::ConstantInitialized);

  inline ScriptException_StackTraceFrame(const ScriptException_StackTraceFrame& from) : ScriptException_StackTraceFrame(nullptr, from) {}
  inline ScriptException_StackTraceFrame(ScriptException_StackTraceFrame&& from) noexcept
      : ScriptException_StackTraceFrame(nullptr, std::move(from)) {}
  inline ScriptException_StackTraceFrame& operator=(const ScriptException_StackTraceFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScriptException_StackTraceFrame& operator=(ScriptException_StackTraceFrame&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScriptException_StackTraceFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScriptException_StackTraceFrame* internal_default_instance() {
    return reinterpret_cast<const ScriptException_StackTraceFrame*>(
        &_ScriptException_StackTraceFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ScriptException_StackTraceFrame& a, ScriptException_StackTraceFrame& b) { a.Swap(&b); }
  inline void Swap(ScriptException_StackTraceFrame* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScriptException_StackTraceFrame* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScriptException_StackTraceFrame* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ScriptException_StackTraceFrame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScriptException_StackTraceFrame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ScriptException_StackTraceFrame& from) { ScriptException_StackTraceFrame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ScriptException_StackTraceFrame* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.ScriptException.StackTraceFrame"; }

 protected:
  explicit ScriptException_StackTraceFrame(::google::protobuf::Arena* arena);
  ScriptException_StackTraceFrame(::google::protobuf::Arena* arena, const ScriptException_StackTraceFrame& from);
  ScriptException_StackTraceFrame(::google::protobuf::Arena* arena, ScriptException_StackTraceFrame&& from) noexcept
      : ScriptException_StackTraceFrame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilenameFieldNumber = 3,
    kLocationFieldNumber = 4,
    kLineFieldNumber = 1,
    kColumnFieldNumber = 2,
  };
  // optional string filename = 3;
  bool has_filename() const;
  void clear_filename() ;
  const std::string& filename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* value);

  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(
      const std::string& value);
  std::string* _internal_mutable_filename();

  public:
  // optional string location = 4;
  bool has_location() const;
  void clear_location() ;
  const std::string& location() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_location(Arg_&& arg, Args_... args);
  std::string* mutable_location();
  PROTOBUF_NODISCARD std::string* release_location();
  void set_allocated_location(std::string* value);

  private:
  const std::string& _internal_location() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_location(
      const std::string& value);
  std::string* _internal_mutable_location();

  public:
  // optional int64 line = 1;
  bool has_line() const;
  void clear_line() ;
  ::int64_t line() const;
  void set_line(::int64_t value);

  private:
  ::int64_t _internal_line() const;
  void _internal_set_line(::int64_t value);

  public:
  // optional int64 column = 2;
  bool has_column() const;
  void clear_column() ;
  ::int64_t column() const;
  void set_column(::int64_t value);

  private:
  ::int64_t _internal_column() const;
  void _internal_set_column(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:googlesql.ScriptException.StackTraceFrame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      66, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ScriptException_StackTraceFrame& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::google::protobuf::internal::ArenaStringPtr location_;
    ::int64_t line_;
    ::int64_t column_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto;
};
// -------------------------------------------------------------------

class ScriptException_Internal final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql.ScriptException.Internal) */ {
 public:
  inline ScriptException_Internal() : ScriptException_Internal(nullptr) {}
  ~ScriptException_Internal() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ScriptException_Internal* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ScriptException_Internal));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ScriptException_Internal(
      ::google::protobuf::internal::ConstantInitialized);

  inline ScriptException_Internal(const ScriptException_Internal& from) : ScriptException_Internal(nullptr, from) {}
  inline ScriptException_Internal(ScriptException_Internal&& from) noexcept
      : ScriptException_Internal(nullptr, std::move(from)) {}
  inline ScriptException_Internal& operator=(const ScriptException_Internal& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScriptException_Internal& operator=(ScriptException_Internal&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScriptException_Internal& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScriptException_Internal* internal_default_instance() {
    return reinterpret_cast<const ScriptException_Internal*>(
        &_ScriptException_Internal_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ScriptException_Internal& a, ScriptException_Internal& b) { a.Swap(&b); }
  inline void Swap(ScriptException_Internal* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScriptException_Internal* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScriptException_Internal* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ScriptException_Internal>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScriptException_Internal& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ScriptException_Internal& from) { ScriptException_Internal::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ScriptException_Internal* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.ScriptException.Internal"; }

 protected:
  explicit ScriptException_Internal(::google::protobuf::Arena* arena);
  ScriptException_Internal(::google::protobuf::Arena* arena, const ScriptException_Internal& from);
  ScriptException_Internal(::google::protobuf::Arena* arena, ScriptException_Internal&& from) noexcept
      : ScriptException_Internal(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStackTraceFieldNumber = 2,
    kStatementTextFieldNumber = 1,
  };
  // repeated .googlesql.ScriptException.StackTraceFrame stack_trace = 2;
  int stack_trace_size() const;
  private:
  int _internal_stack_trace_size() const;

  public:
  void clear_stack_trace() ;
  ::googlesql::ScriptException_StackTraceFrame* mutable_stack_trace(int index);
  ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>* mutable_stack_trace();

  private:
  const ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>& _internal_stack_trace() const;
  ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>* _internal_mutable_stack_trace();
  public:
  const ::googlesql::ScriptException_StackTraceFrame& stack_trace(int index) const;
  ::googlesql::ScriptException_StackTraceFrame* add_stack_trace();
  const ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>& stack_trace() const;
  // optional string statement_text = 1;
  bool has_statement_text() const;
  void clear_statement_text() ;
  const std::string& statement_text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_statement_text(Arg_&& arg, Args_... args);
  std::string* mutable_statement_text();
  PROTOBUF_NODISCARD std::string* release_statement_text();
  void set_allocated_statement_text(std::string* value);

  private:
  const std::string& _internal_statement_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_statement_text(
      const std::string& value);
  std::string* _internal_mutable_statement_text();

  public:
  // @@protoc_insertion_point(class_scope:googlesql.ScriptException.Internal)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      57, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ScriptException_Internal& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::googlesql::ScriptException_StackTraceFrame > stack_trace_;
    ::google::protobuf::internal::ArenaStringPtr statement_text_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto;
};
// -------------------------------------------------------------------

class ScriptException final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql.ScriptException) */ {
 public:
  inline ScriptException() : ScriptException(nullptr) {}
  ~ScriptException() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ScriptException* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ScriptException));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ScriptException(
      ::google::protobuf::internal::ConstantInitialized);

  inline ScriptException(const ScriptException& from) : ScriptException(nullptr, from) {}
  inline ScriptException(ScriptException&& from) noexcept
      : ScriptException(nullptr, std::move(from)) {}
  inline ScriptException& operator=(const ScriptException& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScriptException& operator=(ScriptException&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScriptException& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScriptException* internal_default_instance() {
    return reinterpret_cast<const ScriptException*>(
        &_ScriptException_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ScriptException& a, ScriptException& b) { a.Swap(&b); }
  inline void Swap(ScriptException* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScriptException* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScriptException* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ScriptException>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScriptException& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ScriptException& from) { ScriptException::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ScriptException* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.ScriptException"; }

 protected:
  explicit ScriptException(::google::protobuf::Arena* arena);
  ScriptException(::google::protobuf::Arena* arena, const ScriptException& from);
  ScriptException(::google::protobuf::Arena* arena, ScriptException&& from) noexcept
      : ScriptException(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using StackTraceFrame = ScriptException_StackTraceFrame;
  using Internal = ScriptException_Internal;

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 1,
    kInternalFieldNumber = 2,
  };
  // optional string message = 1;
  bool has_message() const;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // optional .googlesql.ScriptException.Internal internal = 2;
  bool has_internal() const;
  void clear_internal() ;
  const ::googlesql::ScriptException_Internal& internal() const;
  PROTOBUF_NODISCARD ::googlesql::ScriptException_Internal* release_internal();
  ::googlesql::ScriptException_Internal* mutable_internal();
  void set_allocated_internal(::googlesql::ScriptException_Internal* value);
  void unsafe_arena_set_allocated_internal(::googlesql::ScriptException_Internal* value);
  ::googlesql::ScriptException_Internal* unsafe_arena_release_internal();

  private:
  const ::googlesql::ScriptException_Internal& _internal_internal() const;
  ::googlesql::ScriptException_Internal* _internal_mutable_internal();

  public:
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            typename = typename _proto_TypeTraits::Singular>
  inline bool HasExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.Has(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void ClearExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    _impl_._extensions_.ClearExtension(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            typename = typename _proto_TypeTraits::Repeated>
  inline int ExtensionSize(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.ExtensionSize(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<!_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Mutable(id.number(), _field_type, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::ConstType value) {
    _proto_TypeTraits::Set(id.number(), _field_type, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::SetAllocated(id.number(), _field_type, value,
                                    &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void UnsafeArenaSetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::UnsafeArenaSetAllocated(id.number(), _field_type,
                                               value, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  PROTOBUF_NODISCARD inline
      typename _proto_TypeTraits::Singular::MutableType
      ReleaseExtension(
          const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                           _field_type, _is_packed>& id) {
    return _proto_TypeTraits::Release(id.number(), _field_type, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType
  UnsafeArenaReleaseExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::UnsafeArenaRelease(id.number(), _field_type,
                                                 &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<!_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Mutable(id.number(), index, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index, typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Set(id.number(), index, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    typename _proto_TypeTraits::Repeated::MutableType to_add =
        _proto_TypeTraits::Add(id.number(), _field_type, &_impl_._extensions_);
    return to_add;
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Add(id.number(), _field_type, _is_packed, value,
                           &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline const typename _proto_TypeTraits::Repeated::RepeatedFieldType&
  GetRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::GetRepeated(id.number(), _impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::RepeatedFieldType*
  MutableRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<ScriptException, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::MutableRepeated(id.number(), _field_type,
                                              _is_packed, &_impl_._extensions_);
  }
  // @@protoc_insertion_point(class_scope:googlesql.ScriptException)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      41, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ScriptException& from_msg);
    ::google::protobuf::internal::ExtensionSet _extensions_;
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::googlesql::ScriptException_Internal* internal_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ScriptException_StackTraceFrame

// optional int64 line = 1;
inline bool ScriptException_StackTraceFrame::has_line() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ScriptException_StackTraceFrame::clear_line() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t ScriptException_StackTraceFrame::line() const {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.StackTraceFrame.line)
  return _internal_line();
}
inline void ScriptException_StackTraceFrame::set_line(::int64_t value) {
  _internal_set_line(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:googlesql.ScriptException.StackTraceFrame.line)
}
inline ::int64_t ScriptException_StackTraceFrame::_internal_line() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.line_;
}
inline void ScriptException_StackTraceFrame::_internal_set_line(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line_ = value;
}

// optional int64 column = 2;
inline bool ScriptException_StackTraceFrame::has_column() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ScriptException_StackTraceFrame::clear_column() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.column_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t ScriptException_StackTraceFrame::column() const {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.StackTraceFrame.column)
  return _internal_column();
}
inline void ScriptException_StackTraceFrame::set_column(::int64_t value) {
  _internal_set_column(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:googlesql.ScriptException.StackTraceFrame.column)
}
inline ::int64_t ScriptException_StackTraceFrame::_internal_column() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.column_;
}
inline void ScriptException_StackTraceFrame::_internal_set_column(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.column_ = value;
}

// optional string filename = 3;
inline bool ScriptException_StackTraceFrame::has_filename() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ScriptException_StackTraceFrame::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ScriptException_StackTraceFrame::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.StackTraceFrame.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScriptException_StackTraceFrame::set_filename(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:googlesql.ScriptException.StackTraceFrame.filename)
}
inline std::string* ScriptException_StackTraceFrame::mutable_filename() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:googlesql.ScriptException.StackTraceFrame.filename)
  return _s;
}
inline const std::string& ScriptException_StackTraceFrame::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void ScriptException_StackTraceFrame::_internal_set_filename(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(value, GetArena());
}
inline std::string* ScriptException_StackTraceFrame::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.filename_.Mutable( GetArena());
}
inline std::string* ScriptException_StackTraceFrame::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.ScriptException.StackTraceFrame.filename)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.filename_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.filename_.Set("", GetArena());
  }
  return released;
}
inline void ScriptException_StackTraceFrame::set_allocated_filename(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:googlesql.ScriptException.StackTraceFrame.filename)
}

// optional string location = 4;
inline bool ScriptException_StackTraceFrame::has_location() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ScriptException_StackTraceFrame::clear_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.location_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ScriptException_StackTraceFrame::location() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.StackTraceFrame.location)
  return _internal_location();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScriptException_StackTraceFrame::set_location(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.location_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:googlesql.ScriptException.StackTraceFrame.location)
}
inline std::string* ScriptException_StackTraceFrame::mutable_location() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:googlesql.ScriptException.StackTraceFrame.location)
  return _s;
}
inline const std::string& ScriptException_StackTraceFrame::_internal_location() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.location_.Get();
}
inline void ScriptException_StackTraceFrame::_internal_set_location(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.location_.Set(value, GetArena());
}
inline std::string* ScriptException_StackTraceFrame::_internal_mutable_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.location_.Mutable( GetArena());
}
inline std::string* ScriptException_StackTraceFrame::release_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.ScriptException.StackTraceFrame.location)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.location_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.location_.Set("", GetArena());
  }
  return released;
}
inline void ScriptException_StackTraceFrame::set_allocated_location(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.location_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.location_.IsDefault()) {
    _impl_.location_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:googlesql.ScriptException.StackTraceFrame.location)
}

// -------------------------------------------------------------------

// ScriptException_Internal

// optional string statement_text = 1;
inline bool ScriptException_Internal::has_statement_text() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ScriptException_Internal::clear_statement_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.statement_text_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ScriptException_Internal::statement_text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.Internal.statement_text)
  return _internal_statement_text();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScriptException_Internal::set_statement_text(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.statement_text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:googlesql.ScriptException.Internal.statement_text)
}
inline std::string* ScriptException_Internal::mutable_statement_text() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_statement_text();
  // @@protoc_insertion_point(field_mutable:googlesql.ScriptException.Internal.statement_text)
  return _s;
}
inline const std::string& ScriptException_Internal::_internal_statement_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.statement_text_.Get();
}
inline void ScriptException_Internal::_internal_set_statement_text(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.statement_text_.Set(value, GetArena());
}
inline std::string* ScriptException_Internal::_internal_mutable_statement_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.statement_text_.Mutable( GetArena());
}
inline std::string* ScriptException_Internal::release_statement_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.ScriptException.Internal.statement_text)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.statement_text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.statement_text_.Set("", GetArena());
  }
  return released;
}
inline void ScriptException_Internal::set_allocated_statement_text(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.statement_text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.statement_text_.IsDefault()) {
    _impl_.statement_text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:googlesql.ScriptException.Internal.statement_text)
}

// repeated .googlesql.ScriptException.StackTraceFrame stack_trace = 2;
inline int ScriptException_Internal::_internal_stack_trace_size() const {
  return _internal_stack_trace().size();
}
inline int ScriptException_Internal::stack_trace_size() const {
  return _internal_stack_trace_size();
}
inline void ScriptException_Internal::clear_stack_trace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stack_trace_.Clear();
}
inline ::googlesql::ScriptException_StackTraceFrame* ScriptException_Internal::mutable_stack_trace(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:googlesql.ScriptException.Internal.stack_trace)
  return _internal_mutable_stack_trace()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>* ScriptException_Internal::mutable_stack_trace()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:googlesql.ScriptException.Internal.stack_trace)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_stack_trace();
}
inline const ::googlesql::ScriptException_StackTraceFrame& ScriptException_Internal::stack_trace(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.Internal.stack_trace)
  return _internal_stack_trace().Get(index);
}
inline ::googlesql::ScriptException_StackTraceFrame* ScriptException_Internal::add_stack_trace() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::googlesql::ScriptException_StackTraceFrame* _add = _internal_mutable_stack_trace()->Add();
  // @@protoc_insertion_point(field_add:googlesql.ScriptException.Internal.stack_trace)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>& ScriptException_Internal::stack_trace() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:googlesql.ScriptException.Internal.stack_trace)
  return _internal_stack_trace();
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>&
ScriptException_Internal::_internal_stack_trace() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stack_trace_;
}
inline ::google::protobuf::RepeatedPtrField<::googlesql::ScriptException_StackTraceFrame>*
ScriptException_Internal::_internal_mutable_stack_trace() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.stack_trace_;
}

// -------------------------------------------------------------------

// ScriptException

// optional string message = 1;
inline bool ScriptException::has_message() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ScriptException::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ScriptException::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScriptException::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:googlesql.ScriptException.message)
}
inline std::string* ScriptException::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:googlesql.ScriptException.message)
  return _s;
}
inline const std::string& ScriptException::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void ScriptException::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.message_.Set(value, GetArena());
}
inline std::string* ScriptException::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* ScriptException::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.ScriptException.message)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void ScriptException::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:googlesql.ScriptException.message)
}

// optional .googlesql.ScriptException.Internal internal = 2;
inline bool ScriptException::has_internal() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.internal_ != nullptr);
  return value;
}
inline void ScriptException::clear_internal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.internal_ != nullptr) _impl_.internal_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::googlesql::ScriptException_Internal& ScriptException::_internal_internal() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql::ScriptException_Internal* p = _impl_.internal_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql::ScriptException_Internal&>(::googlesql::_ScriptException_Internal_default_instance_);
}
inline const ::googlesql::ScriptException_Internal& ScriptException::internal() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql.ScriptException.internal)
  return _internal_internal();
}
inline void ScriptException::unsafe_arena_set_allocated_internal(::googlesql::ScriptException_Internal* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.internal_);
  }
  _impl_.internal_ = reinterpret_cast<::googlesql::ScriptException_Internal*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql.ScriptException.internal)
}
inline ::googlesql::ScriptException_Internal* ScriptException::release_internal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::googlesql::ScriptException_Internal* released = _impl_.internal_;
  _impl_.internal_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql::ScriptException_Internal* ScriptException::unsafe_arena_release_internal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql.ScriptException.internal)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::googlesql::ScriptException_Internal* temp = _impl_.internal_;
  _impl_.internal_ = nullptr;
  return temp;
}
inline ::googlesql::ScriptException_Internal* ScriptException::_internal_mutable_internal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.internal_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql::ScriptException_Internal>(GetArena());
    _impl_.internal_ = reinterpret_cast<::googlesql::ScriptException_Internal*>(p);
  }
  return _impl_.internal_;
}
inline ::googlesql::ScriptException_Internal* ScriptException::mutable_internal() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::googlesql::ScriptException_Internal* _msg = _internal_mutable_internal();
  // @@protoc_insertion_point(field_mutable:googlesql.ScriptException.internal)
  return _msg;
}
inline void ScriptException::set_allocated_internal(::googlesql::ScriptException_Internal* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.internal_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.internal_ = reinterpret_cast<::googlesql::ScriptException_Internal*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql.ScriptException.internal)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fproto_2fscript_5fexception_2eproto_2epb_2eh
